export const games = [

  // ─────────────────────────────────────────────
  // The Midnight Mall
  // ─────────────────────────────────────────────

  {
    id: "the-midnight-mall-mixed-reading-skills-2",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_2ndGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "the-midnight-mall-main-idea-and-supporting-details-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/main-idea/mainIdea_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-main-idea-and-supporting-details-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-figurative-language-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-context-clues-and-vocabulary-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "context-clues-and-vocabulary",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/context-clues/contextClues_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-context-clues-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-story-elements-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/story-elements/storyElements_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-story-elements-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-poetry-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/poetry/poetry_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-poetry-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-grammar-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/grammar/grammar_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-grammar-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-making-inferences-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/making-inferences/makingInferences_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-making-inferences-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-text-features-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-features",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/text-features/textFeatures_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-text-structures-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-structures",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/text-structures/textStructures_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-authors-purpose-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "authors-purpose",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/authors-purpose/authorsPurpose_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-character-traits-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "character-traits",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/reading/character-traits/characterTraits_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-2",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/all/math_2ndGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/all/math_4thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/all/math_5thGrade.js",
  },
  {
    id: "the-midnight-mall-multiplication-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-multiplication-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "the-midnight-mall-order-of-operations-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/math/orderOfOperations/orderOfOperations_5thGrade.js",
  },
  {
    id: "the-midnight-mall-growth-mindset-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "social-emotional-learning",
    topic: "growth-mindset",
    standards: [],
    path: "resource/escape-the-midnight-mall/topic/social-emotional-learning/growthMindset_4th5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Pickle's Playground
  // ─────────────────────────────────────────────

  {
    id: "pickles-playground-mixed-reading-skills-3",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/pickles-playground/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "pickles-playground-mixed-reading-skills-4",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/pickles-playground/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "pickles-playground-mixed-reading-skills-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/pickles-playground/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "pickles-playground-main-idea-and-supporting-details-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/pickles-playground/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "pickles-playground-figurative-language-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/pickles-playground/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "pickles-playground-context-clues-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/pickles-playground/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "pickles-playground-story-elements-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/pickles-playground/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "pickles-playground-poetry-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/pickles-playground/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "pickles-playground-making-inferences-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/pickles-playground/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "pickles-playground-grammar-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/pickles-playground/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "pickles-playground-authors-purpose-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "authors-purpose",
    standards: [],
    path: "resource/pickles-playground/topic/reading/authors-purpose/authorsPurpose_4th5thGrade.js",
  },
  {
    id: "pickles-playground-character-traits-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "character-traits",
    standards: [],
    path: "resource/pickles-playground/topic/reading/character-traits/characterTraits_4th5thGrade.js",
  },
  {
    id: "pickles-playground-text-structures-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-structures",
    standards: [],
    path: "resource/pickles-playground/topic/reading/text-structures/textStructures_4th5thGrade.js",
  },
  {
    id: "pickles-playground-growth-mindset-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "social-emotional-learning",
    topic: "growth-mindset",
    standards: [],
    path: "resource/pickles-playground/topic/social-emotional-learning/growthMindset_4th5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Beehive Blitz
  // ─────────────────────────────────────────────

  {
    id: "beehive-blitz-mixed-reading-skills-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "beehive-blitz-mixed-reading-skills-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-reading-skills-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "beehive-blitz-context-clues-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-figurative-language-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-main-idea-and-supporting-details-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-poetry-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-story-elements-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-making-inferences-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-grammar-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/beehive-blitz/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/math/all/math_4thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/beehive-blitz/topic/math/all/math_5thGrade.js",
  },
  {
    id: "beehive-blitz-fractions-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/beehive-blitz/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "beehive-blitz-fractions-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/beehive-blitz/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "beehive-blitz-fractions-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/beehive-blitz/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "beehive-blitz-multiplication-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/beehive-blitz/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "beehive-blitz-multiplication-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/beehive-blitz/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "beehive-blitz-order-of-operations-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    path: "resource/beehive-blitz/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Camp Calamari
  // ─────────────────────────────────────────────

  {
    id: "camp-calamari-mixed-reading-skills-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/camp-calamari/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "camp-calamari-mixed-reading-skills-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/camp-calamari/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "camp-calamari-mixed-reading-skills-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/camp-calamari/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "camp-calamari-context-clues-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/camp-calamari/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "camp-calamari-figurative-language-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/camp-calamari/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "camp-calamari-main-idea-and-supporting-details-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/camp-calamari/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "camp-calamari-poetry-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/camp-calamari/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "camp-calamari-story-elements-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/camp-calamari/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "camp-calamari-making-inferences-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/camp-calamari/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "camp-calamari-grammar-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/camp-calamari/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/camp-calamari/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/camp-calamari/topic/math/all/math_4thGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/camp-calamari/topic/math/all/math_5thGrade.js",
  },
  {
    id: "camp-calamari-fractions-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/camp-calamari/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "camp-calamari-fractions-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/camp-calamari/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "camp-calamari-fractions-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/camp-calamari/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "camp-calamari-multiplication-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/camp-calamari/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "camp-calamari-multiplication-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/camp-calamari/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "camp-calamari-order-of-operations-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    path: "resource/camp-calamari/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // The Hasty Harvest
  // ─────────────────────────────────────────────

  {
    id: "the-hasty-harvest-mixed-reading-skills-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-reading-skills-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-reading-skills-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-main-idea-and-supporting-details-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-figurative-language-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-context-clues-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-story-elements-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-poetry-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-making-inferences-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-grammar-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/the-hasty-harvest/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/all/math_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/all/math_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-multiplication-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-multiplication-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-order-of-operations-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    path: "resource/the-hasty-harvest/topic/math/orderOfOperations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Yeti and the Yams
  // ─────────────────────────────────────────────

  {
    id: "yeti-and-the-yams-mixed-reading-skills-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-reading-skills-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-reading-skills-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-main-idea-and-supporting-details-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-figurative-language-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-context-clues-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-story-elements-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-poetry-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-making-inferences-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-grammar-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-multiplication-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-multiplication-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-order-of-operations-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    path: "resource/the-yeti-and-the-yam/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Cupid's Countdown
  // ─────────────────────────────────────────────

  {
    id: "cupids-countdown-mixed-reading-skills-3",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/cupids-countdown/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "cupids-countdown-mixed-reading-skills-4",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/cupids-countdown/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "cupids-countdown-mixed-reading-skills-5",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/cupids-countdown/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Rainbow Rescue
  // ─────────────────────────────────────────────

  {
    id: "rainbow-rescue-mixed-reading-skills-3",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/rainbow-rescue/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "rainbow-rescue-mixed-reading-skills-4",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/rainbow-rescue/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "rainbow-rescue-mixed-reading-skills-5",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/rainbow-rescue/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Eggworld Emergency
  // ─────────────────────────────────────────────

  {
    id: "eggworld-emergency-mixed-reading-skills-3",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/eggworld-emergency/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "eggworld-emergency-mixed-reading-skills-4",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/eggworld-emergency/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "eggworld-emergency-mixed-reading-skills-5",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/eggworld-emergency/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Final Bell Breakout
  // ─────────────────────────────────────────────

  {
    id: "final-bell-breakout-mixed-reading-skills-2",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [2],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/final-bell-breakout/topic/reading/all/reading_2ndGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-3",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/final-bell-breakout/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-4",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/final-bell-breakout/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-5",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/final-bell-breakout/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Paradise Panic
  // ─────────────────────────────────────────────

  {
    id: "paradise-panic-mixed-reading-skills-3",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/paradise-panic/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "paradise-panic-mixed-reading-skills-4",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/paradise-panic/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "paradise-panic-mixed-reading-skills-5",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/paradise-panic/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Funhouse Fright
  // ─────────────────────────────────────────────

  {
    id: "funhouse-fright-mixed-reading-skills-3",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/funhouse-fright/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "funhouse-fright-mixed-reading-skills-4",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/funhouse-fright/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "funhouse-fright-mixed-reading-skills-5",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/funhouse-fright/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Turkey Takedown
  // ─────────────────────────────────────────────

  {
    id: "turkey-takedown-mixed-reading-skills-3",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/turkey-takedown/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "turkey-takedown-mixed-reading-skills-4",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/turkey-takedown/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "turkey-takedown-mixed-reading-skills-5",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/turkey-takedown/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Wacky Workshop
  // ─────────────────────────────────────────────

  {
    id: "wacky-workshop-mixed-reading-skills-3",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/wacky-workshop/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "wacky-workshop-mixed-reading-skills-4",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/wacky-workshop/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "wacky-workshop-mixed-reading-skills-5",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    path: "resource/wacky-workshop/topic/reading/all/reading_5thGrade.js",
  },

];
