export const games = [

  // ─────────────────────────────────────────────
  // The Midnight Mall
  // ─────────────────────────────────────────────

  {
    id: "the-midnight-mall-mixed-reading-skills-2",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Key Details",
      "Story Elements",
      "Context Clues and Vocabulary",
      "Text Features",
      "Poetry",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/all/thumbnail-2nd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_2ndGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/all/thumbnail-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/all/thumbnail-4th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-reading-skills-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Figurative Language",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/all/thumbnail-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "the-midnight-mall-main-idea-and-supporting-details-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Idea",
      "Main Idea and Details of a One-Paragraph Text",
      "Main Idea and Details of Multiple Texts",
      "Main Topic and the Focus of Specific Paragraphs",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/main-idea/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/main-idea/mainIdea_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-main-idea-and-supporting-details-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Ideas and Supporting Details of Short Passages",
      "Main Idea and Supporting Details of a Poem",
      "Main Ideas and Supporting Details of Informational Texts; Topic",
      "Main Idea and Supporting Details of a Short Story",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/main-idea/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-figurative-language-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes",
      "Metaphors",
      "Hyperbole",
      "Personification",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/figurative-language/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-context-clues-and-vocabulary-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "context-clues-and-vocabulary",
    standards: [],
    skills: [
      "Context Clues as Definitions",
      "Roots, Prefixes, and Suffixes",
      "Compound Words and Shades of Meaning",
      "Context Clues as Examples",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/context-clues/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/context-clues/contextClues_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-context-clues-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Examples",
      "Context Clues as Definitions",
      "Context Clues as Antonyms",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/context-clues/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-story-elements-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Key Details",
      "Structure",
      "Characters",
      "Theme",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/story-elements/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/story-elements/storyElements_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-story-elements-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Theme and Supporting Details",
      "Setting",
      "Character",
      "Plot and Conflict",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/story-elements/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-poetry-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Elements and Structure",
      "Comprehension",
      "Language and Vocabulary",
      "Central Message or Lesson",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/poetry/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/poetry/poetry_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-poetry-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Reading Comprehension",
      "Figurative Language",
      "Poetic Elements",
      "Author's Purpose",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/poetry/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-grammar-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Parts of Speech",
      "Capitalization and Punctuation",
      "Sentence Structure",
      "Commonly Confused Words",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/grammar/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/grammar/grammar_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-grammar-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Parts of Speech",
      "Punctuation and Capitalization",
      "Sentence Structure",
      "Common Errors",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/grammar/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-making-inferences-2-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2, 3],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences From a Visual",
      "Making Inferences From Fiction",
      "Making Inferences From Nonfiction",
      "Solving Riddles",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/making-inferences/thumbnail-2nd-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/making-inferences/makingInferences_2nd3rdGrade.js",
  },
  {
    id: "the-midnight-mall-making-inferences-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About a Fictional Story",
      "Making Inferences About a Nonfiction Text",
      "Making Inferences About Related Texts",
      "Solving Riddles",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/making-inferences/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-text-features-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-features",
    standards: [],
    skills: [
      "Print Features",
      "Image Features",
      "Navigation Features",
      "Data Display Features",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/text-features/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/text-features/textFeatures_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-text-structures-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-structures",
    standards: [],
    skills: [
      "",
      "",
      "",
      "",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/text-structures/thumbnail-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/text-structures/textStructures_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-authors-purpose-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "authors-purpose",
    standards: [],
    skills: [
      "PIE: Persuade, Inform, and Entertain",
      "ED: Explain and Describe",
      "Reasons, Evidence, and Audience",
      "Compare and Contrast",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/authors-purpose/thumbnail-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/authors-purpose/authorsPurpose_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-character-traits-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "character-traits",
    standards: [],
    skills: [
      "Identify Character Traits",
      "Infer Character Traits",
      "Character Traits, Feelings, and Motivations",
      "Compare and Contrast Character Traits",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/character-traits/thumbnail-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/reading/character-traits/characterTraits_4th5thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-2",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [2],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Add and Subtract Within 20",
      "Add and Subtract Within 100",
      "Place Value",
      "Word Problems With Addition and Subtraction",
      "Length and Shapes",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/all-standards/thumbnail-2nd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/all/math_2ndGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems with Addition and Subtraction",
      "Multiplication and Division Facts",
      "Round to the Nearest 10 or 100",
      "Measure and Compare Length in Units",
      "Fractions of Shapes",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/all-standards/thumbnail-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems with Addition, Subtraction, and Multiplication",
      "Area and Perimeter",
      "Place Value and Rounding",
      "Fractions of Shapes and Number Lines",
      "Computation: Addition, Subtraction, Multiplication, and Division",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/all-standards/thumbnail-4th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/all/math_4thGrade.js",
  },
  {
    id: "the-midnight-mall-mixed-math-skills-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems with All Operations",
      "Calculate Volume",
      "Add and Subtract Decimals to Hundredths",
      "Fractions and Mixed Numbers",
      "Identify Lines and Angles",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/all-standards/thumbnail-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/all/math_5thGrade.js",
  },
  {
    id: "the-midnight-mall-multiplication-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Facts",
      "Determine the Unknown Number in a Multiplication Equation",
      "Properties of Multiplication; Arrays",
      "Multi-Step Word Problems with Addition, Subtraction, and Multiplication",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/multiplication/preview-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-multiplication-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplicative Comparison Word Problems",
      "Factors and Multiples",
      "Mutiplication in Base Ten",
      "Multi-Digit Multiplication",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/multiplication/preview-4th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-3",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fractions on a Number Line",
      "Equivalent Fractions",
      "Compare Fractions With Like Numerators and Denominators",
      "Whole Numbers as Fractions",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/fractions/preview-3rd-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-4",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Like Denominators",
      "Compare Fractions With Unlike Denominators",
      "Add and Subtract Mixed Numbers",
      "Multiply Fractions by Whole Numbers",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/fractions/preview-4th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "the-midnight-mall-fractions-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions and Mixed Numbers With Unlike Denominators",
      "Multiply Fractions, Mixed Numbers, and Whole Numbers",
      "Divide Unit Fractions and Whole Numbers",
      "Fraction Word Problems With All Four Operations",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/fractions/preview-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "the-midnight-mall-order-of-operations-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    skills: [
      "Equations With All Four Operations",
      "Word Problems",
      "Sort Equations as True or False",
      "Equations With Exponents",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/math/order-of-operations/preview-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/math/orderOfOperations/orderOfOperations_5thGrade.js",
  },
  {
    id: "the-midnight-mall-growth-mindset-4-5",
    title: "The Midnight Mall",
    season: "all-year",
    grades: [4, 5],
    subject: "social-emotional-learning",
    topic: "growth-mindset",
    standards: [],
    skills: [
      "Growth Mindset vs. Fixed Mindset",
      "The Power of \"Yet\"",
      "Reframing Negative Self-Talk",
      "Learning From Mistakes and Failures",
    ],
    thumbnail: "resource/escape-the-midnight-mall/assets/branding/social-emotional-learning/growth-mindset/preview-4th-5th-grade.png",
    path: "resource/escape-the-midnight-mall/topic/social-emotional-learning/growthMindset_4th5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Pickle's Playground
  // ─────────────────────────────────────────────

  {
    id: "pickles-playground-mixed-reading-skills-3",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/pickles-playground/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "pickles-playground-mixed-reading-skills-4",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/pickles-playground/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "pickles-playground-mixed-reading-skills-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Ideas: Compare and Contrast",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "pickles-playground-main-idea-and-supporting-details-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Compare and Contrast Two Main Ideas",
      "Main Idea and Supporting Details of an Informational Text",
      "Main Idea and Supporting Details of a Narrative Text",
      "Two Main Ideas in a Single Text",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/main-idea/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "pickles-playground-figurative-language-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes and Metaphors",
      "Hyperbole and Personification",
      "Onomatopoeia and Alliteration ",
      "Idioms, Adages, and Proverbs",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/figurative-language/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "pickles-playground-context-clues-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Definitions and Examples",
      "Context Clues as Synonyms and Antonyms",
      "Context Clues as Affixes",
      "Context Clues as Root Words",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/context-clues/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "pickles-playground-story-elements-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Theme and Key Details",
      "Characters and Point of View",
      "Setting",
      "Plot, Conflict, and Events",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/story-elements/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "pickles-playground-poetry-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Elements and Structure",
      "Topic, Theme, and Key Details",
      "Figurative Language",
      "Author's Purpose and Point of View",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/poetry/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "pickles-playground-making-inferences-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About a Fictional Story",
      "Making Inferences About a Nonfiction Text",
      "Making Inferences About Related Texts",
      "Solving Riddles",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/making-inferences/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "pickles-playground-grammar-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Parts of Speech",
      "Punctuation and Capitalization",
      "Sentence Structure",
      "Common Errors",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/grammar/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "pickles-playground-authors-purpose-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "authors-purpose",
    standards: [],
    skills: [
      "PIE: Persuade, Inform, and Entertain",
      "ED: Explain and Describe",
      "Reasons, Evidence, and Audience",
      "Compare and Contrast Author's Purpose",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/context-clues/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/authors-purpose/authorsPurpose_4th5thGrade.js",
  },
  {
    id: "pickles-playground-character-traits-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "character-traits",
    standards: [],
    skills: [
      "Identify Character Traits",
      "Infer Character Traits",
      "Character Traits, Feelings, and Motivations",
      "Compare and Contrast Character Traits",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/context-clues/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/character-traits/characterTraits_4th5thGrade.js",
  },
  {
    id: "pickles-playground-text-structures-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "reading",
    topic: "text-structures",
    standards: [],
    skills: [
      "",
      "",
      "",
      "",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/reading/context-clues/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/reading/text-structures/textStructures_4th5thGrade.js",
  },
  {
    id: "pickles-playground-growth-mindset-4-5",
    title: "Pickle's Playground",
    season: "all-year",
    grades: [4, 5],
    subject: "social-emotional-learning",
    topic: "growth-mindset",
    standards: [],
    skills: [
      "Growth Mindset vs. Fixed Mindset",
      "The Power of Yet",
      "Learning from Mistakes and Failure",
      "Reframing Negative Self-Talk",
    ],
    thumbnail: "resource/pickles-playground/assets/branding/social-emotional-learning/growth-mindset/thumbnail-4th-5th-grade.png",
    path: "resource/pickles-playground/topic/social-emotional-learning/growthMindset_4th5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Beehive Blitz
  // ─────────────────────────────────────────────

  {
    id: "beehive-blitz-mixed-reading-skills-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/beehive-blitz/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "beehive-blitz-mixed-reading-skills-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/beehive-blitz/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-reading-skills-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Figurative Language",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "beehive-blitz-context-clues-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Definitions and Examples",
      "Context Clues as Synonyms and Antonyms",
      "Context Clues as Affixes",
      "Context Clues as Root Words",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/context-clues/preview-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-figurative-language-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes and Metaphors",
      "Hyperbole and Personification",
      "Onomatopoeia and Alliteration",
      "Idioms, Adages, and Proverbs",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/figurative-language/preview-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-main-idea-and-supporting-details-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Ideas and Supporting Details of Short Stories",
      "Main Idea and Supporting Details of an Informational Text",
      "Multiple Main Ideas",
      "Compare and Contrast Main Ideas",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/main-idea/preview-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-poetry-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Poetic Elements and Structure",
      "Theme and Key Details",
      "Figurative Language",
      "Author's Purpose and Point of View",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/poetry/preview-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-story-elements-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Setting",
      "Theme and Key Details",
      "Plot, Conflict, and Events",
      "Character Traits and Point of View",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/story-elements/preview-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-making-inferences-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About an Informational Text",
      "Making Inferences About a Fictional Text",
      "Making Inferences About Multiple Related Texts",
      "Making Inferences About a Visual",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/making-inferences/thumbnail-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-grammar-4-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Punctuation and Capitalization",
      "Parts of Speech",
      "Sentence Structure",
      "Common Errors",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/reading/grammar/thumbnail-4th-5th-grade.png",
    path: "resource/beehive-blitz/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multiplication and Division Facts",
      "Two Step Word Problems With Addition and Subtration",
      "Place Value and Rounding",
      "Area and Perimeter",
      "Fractions of Shapes and Number Lines",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/all/thumbnail-3rd-grade.png",
    path: "resource/beehive-blitz/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Place Value and Rounding",
      "Area and Perimeter",
      "Identify Lines and Angles",
      "Fractions and Mixed Numbers",
      "Multi-Step Word Problems With All Four Operations",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/all/thumbnail-4th-grade.png",
    path: "resource/beehive-blitz/topic/math/all/math_4thGrade.js",
  },
  {
    id: "beehive-blitz-mixed-math-skills-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Decimals",
      "Volume",
      "Fractions and Mixed Numbers With All Four Operations",
      "Graph on a Coordinate Plane",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/all/thumbnail-5th-grade.png",
    path: "resource/beehive-blitz/topic/math/all/math_5thGrade.js",
  },
  {
    id: "beehive-blitz-fractions-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fractions on a Number Line",
      "Equivalent Fractions",
      "Fractions as Whole Numbers",
      "Compare Fractions",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/fractions/preview-3rd-grade.png",
    path: "resource/beehive-blitz/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "beehive-blitz-fractions-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Like Denominators",
      "Add and Subtract Mixed Numbers With Like Denominators",
      "Compare Fractions",
      "Fraction Word Problems With Whole Numbers",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/fractions/preview-4th-grade.png",
    path: "resource/beehive-blitz/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "beehive-blitz-fractions-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Unlike Denominators",
      "Multiply Fractions and Whole Numbers",
      "Divide Unit Fractions and Whole Numbers",
      "Word Problems With All Four Operations",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/fractions/preview-5th-grade.png",
    path: "resource/beehive-blitz/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "beehive-blitz-multiplication-3",
    title: "Beehive Blitz",
    season: "spring",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Facts",
      "Find the Unknown Number in an Equation",
      "Word Problems",
      "Properties of Multiplication; Arrays",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/multiplication/preview-3rd-grade.png",
    path: "resource/beehive-blitz/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "beehive-blitz-multiplication-4",
    title: "Beehive Blitz",
    season: "spring",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Word Problems",
      "Base Ten Multiplication",
      "Multi-Digit Multiplication",
      "Factors and Multiples",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/multiplication/preview-4th-grade.png",
    path: "resource/beehive-blitz/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "beehive-blitz-order-of-operations-5",
    title: "Beehive Blitz",
    season: "spring",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    skills: [
      "Equations With All Four Operations",
      "Word Problems",
      "Equations With Exponents",
      "Compare Equations",
    ],
    thumbnail: "resource/beehive-blitz/assets/branding/math/order-of-operations/preview-5th-grade.png",
    path: "resource/beehive-blitz/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Camp Calamari
  // ─────────────────────────────────────────────

  {
    id: "camp-calamari-mixed-reading-skills-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/camp-calamari/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "camp-calamari-mixed-reading-skills-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/camp-calamari/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "camp-calamari-mixed-reading-skills-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/camp-calamari/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "camp-calamari-context-clues-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Definitions and Examples",
      "Context Clues as Synonyms and Antonyms",
      "Context Clues as Roots and Affixes",
      "Context Clues as Causes and Effects",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/context-clues/preview-4th5th-grade.png",
    path: "resource/camp-calamari/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "camp-calamari-figurative-language-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes and Metaphors",
      "Hyperbole and Personification",
      "Onomatopoeia and Alliteration",
      "Idioms, Adages, and Proverbs",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/figurative-language/preview-4th5th-grade.png",
    path: "resource/camp-calamari/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "camp-calamari-main-idea-and-supporting-details-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Idea and Supporting Details of a Narrative Text",
      "Main Idea and Supporting Details of an Informational Text",
      "Two Main Ideas and Supporting Details",
      "Compare and Contrast Main Ideas and Supporting Details",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/main-idea/preview-4th5th-grade.png",
    path: "resource/camp-calamari/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "camp-calamari-poetry-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Elements and Structure",
      "Theme and Key Details",
      "Figurative Language",
      "Author's Purpose and Point of View",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/poetry/preview-4th5th-grade.png",
    path: "resource/camp-calamari/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "camp-calamari-story-elements-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Theme and Key Details",
      "Setting",
      "Plot, Conflict, and Events",
      "Characters and Point of View",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/story-elements/preview-4th5th-grade.png",
    path: "resource/camp-calamari/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "camp-calamari-making-inferences-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About an Informational Text",
      "Making Inferences About a Fictional Text",
      "Making Inferences About a Visual",
      "Making Inferences About Multiple Related Texts",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/making-inferences/thumbnail-4th-5th-grade.png",
    path: "resource/camp-calamari/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "camp-calamari-grammar-4-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Punctuation and Capitalization",
      "Sentence Structure",
      "Parts of Speech",
      "Common Errors",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/reading/grammar/thumbnail-4th-5th-grade.png",
    path: "resource/camp-calamari/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Two-Step Word Problems With Addition and Subtraction",
      "Multiplication and Division Facts",
      "Place Value and Rounding",
      "Area and Perimeter",
      "Fractions of Shapes and Number Lines",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/all/thumbnail-3rd-grade.png",
    path: "resource/camp-calamari/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Place Value and Rounding",
      "Multi-Step Word Problems With All Four Operations",
      "Area and Perimeter",
      "Fractions and Mixed Numbers with Addition, Subtraction, & Multiplication",
      "Identify Lines and Angles",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/all/thumbnail-4th-grade.png",
    path: "resource/camp-calamari/topic/math/all/math_4thGrade.js",
  },
  {
    id: "camp-calamari-mixed-math-skills-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Volume",
      "Decimal Computation With All Four Operations",
      "Fraction and Mixed Number Computation With All Four Operations",
      "Graph on a Coordinate Plane",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/all/thumbnail-5th-grade.png",
    path: "resource/camp-calamari/topic/math/all/math_5thGrade.js",
  },
  {
    id: "camp-calamari-fractions-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fractions on Number Lines",
      "Equivalent Fractions",
      "Fractions as Whole Numbers",
      "Compare Fractions",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/fractions/preview-3rd-grade.png",
    path: "resource/camp-calamari/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "camp-calamari-fractions-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fraction Word Problems With Addition and Subtraction",
      "Add and Subtract Mixed Numbers",
      "Compare Fractions",
      "Multiply Fractions by Whole Numbers",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/fractions/preview-4th-grade.png",
    path: "resource/camp-calamari/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "camp-calamari-fractions-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions and Mixed Numbers With Unlike Denominators",
      "Multiply Fractions and Whole Numbers",
      "Divide Unit Fractions and Whole Numbers",
      "Fraction Word Problems With All Four Operations",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/fractions/preview-5th-grade.png",
    path: "resource/camp-calamari/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "camp-calamari-multiplication-3",
    title: "Camp Calamari",
    season: "summer",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Facts",
      "Determine the Unknown Number in an Equation",
      "Word Problems",
      "Properties of Multiplication; Arrays",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/multiplication/preview-3rd-grade.png",
    path: "resource/camp-calamari/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "camp-calamari-multiplication-4",
    title: "Camp Calamari",
    season: "summer",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Word Problems",
      "Base Ten Multiplication",
      "Multi-Digit Multiplication",
      "Factors and Multiples",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/multiplication/preview-4th-grade.png",
    path: "resource/camp-calamari/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "camp-calamari-order-of-operations-5",
    title: "Camp Calamari",
    season: "summer",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    skills: [
      "Computation With All Four Operations",
      "Equations With Exponents",
      "Equations With Decimals",
      "Word Problems With All Four Operations",
    ],
    thumbnail: "resource/camp-calamari/assets/branding/math/order-of-operations/preview-5th-grade.png",
    path: "resource/camp-calamari/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // The Hasty Harvest
  // ─────────────────────────────────────────────

  {
    id: "the-hasty-harvest-mixed-reading-skills-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-reading-skills-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-reading-skills-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Figurative Language",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-main-idea-and-supporting-details-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Ideas and Supporting Details of Paragraphs",
      "Main Idea and Supporting Details of a Poem",
      "Main Idea and Supporting Details of an Informational Text",
      "Main Idea and Supporting Details of a Short Story",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/main-idea/preview-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-figurative-language-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes",
      "Metaphors",
      "Personification",
      "Hyperbole",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/figurative-language/preview-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-context-clues-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Examples",
      "Context Clues as Definitions",
      "Context Clues as Synonyms",
      "Context Clues as Antonyms",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/context-clues/preview-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-story-elements-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Setting",
      "Characters",
      "Conflict and Plot",
      "Theme and Supporting Details",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/story-elements/preview-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-poetry-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Poetic Elements",
      "Reading Comprehension",
      "Figurative Language",
      "Author's Purpose",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/poetry/preview-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-making-inferences-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About a Fictional Story",
      "Making Inferences About a Nonfiction Text",
      "Making Inferences About Related Texts",
      "Solving Riddles",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/making-inferences/thumbnail-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-grammar-4-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Parts of Speech",
      "Punctuation and Capitalization",
      "Sentence Structure",
      "Common Errors",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/reading/grammar/thumbnail-4th-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With Addition and Subtraction",
      "Multiplication and Division Facts",
      "Round to the Nearest 10 or 100",
      "Measure and Compare Length in Units",
      "Fractions of Shapes and Number Lines",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/all-standards/thumbnail-3rd-grade.png",
    path: "resource/the-hasty-harvest/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Area and Perimeter",
      "Computation With All Four Operations",
      "Fractions of Shapes and Number Lines",
      "Round to Any Place",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/all-standards/thumbnail-4th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/all/math_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-mixed-math-skills-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Calculate Volume",
      "Add and Subtract Decimals to Hundredths",
      "Add and Subtract Fractions and Mixed Numbers With Like Denominators",
      "Identify Lines and Angles",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/all-standards/thumbnail-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/all/math_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-multiplication-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Facts",
      "Determine the Unknown Number in a Multiplication Equation",
      "Word Problems",
      "Properties of Multiplication; Arrays",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/multiplication/preview-3rd-grade.png",
    path: "resource/the-hasty-harvest/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-multiplication-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplicative Comparison Word Problems",
      "Multiplication in Base Ten; Understand Place Value",
      "Factors and Multiples",
      "Muti-Digit Multiplication",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/multiplication/preview-4th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-3",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fractions on Number Lines",
      "Compare Fractions",
      "Whole Numbers as Fractions",
      "Equivalent Fractions",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/fractions/preview-3rd-grade.png",
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-4",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Like Denominators",
      "Compare Fractions",
      "Add and Subtract Mixed Numbers With Like Denominators",
      "Multiply Fractions by Whole Numbers",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/fractions/preview-4th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "the-hasty-harvest-fractions-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions and Mixed Numbers With Unlike Denominators",
      "Multiply Fractions, Mixed Numbers, and Whole Numbers",
      "Divide Unit Fractions and Whole Numbers",
      "Fraction Word Problems With All Four Operations",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/fractions/preview-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "the-hasty-harvest-order-of-operations-5",
    title: "The Hasty Harvest",
    season: "fall",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    skills: [
      "Equations With All Four Operations",
      "Order of Operations Word Problems",
      "Compare Order of Operations Equations",
      "Order of Operations With Exponents",
    ],
    thumbnail: "resource/the-hasty-harvest/assets/branding/math/order-of-operations/preview-5th-grade.png",
    path: "resource/the-hasty-harvest/topic/math/orderOfOperations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Yeti and the Yams
  // ─────────────────────────────────────────────

  {
    id: "yeti-and-the-yams-mixed-reading-skills-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-reading-skills-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Similes and Metaphors",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-reading-skills-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea",
      "Poetry",
      "Figurative Language",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/all/reading_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-main-idea-and-supporting-details-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "main-idea-and-supporting-details",
    standards: [],
    skills: [
      "Main Idea of a Short Story",
      "Main Idea of a Poem",
      "Main Ideas of Informational Texts",
      "Compare and Contrast Main Ideas",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/main-idea/preview-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/main-idea/mainIdea_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-figurative-language-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "figurative-language",
    standards: [],
    skills: [
      "Similes and Metaphors",
      "Hyperbole and Onomatopoeia",
      "Personification",
      "Idioms, Adages, and Proverbs",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/figurative-language/preview-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/figurative-language/figurativeLanguage_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-context-clues-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "context-clues",
    standards: [],
    skills: [
      "Context Clues as Definitions",
      "Context Clues as Synonyms and Antonyms",
      "Context Clues as Examples",
      "Context Clues as Prefixes and Suffixes",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/context-clues/preview-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/context-clues/contextClues_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-story-elements-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "story-elements",
    standards: [],
    skills: [
      "Theme and Supporting Details",
      "Setting",
      "Plot and Conflict",
      "Character and Point of View",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/story-elements/preview-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/story-elements/storyElements_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-poetry-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "poetry",
    standards: [],
    skills: [
      "Poetic Elements",
      "Figurative Language",
      "Poetry Comprehension",
      "Author's Purpose",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/poetry/preview-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/poetry/poetry_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-making-inferences-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "making-inferences",
    standards: [],
    skills: [
      "Making Inferences About a Fictional Story",
      "Making Inferences About a Nonfiction Text",
      "Making Inferences About Related Texts",
      "Solving Riddles",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/making-inferences/thumbnail-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/making-inferences/makingInferences_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-grammar-4-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4, 5],
    subject: "reading",
    topic: "grammar",
    standards: [],
    skills: [
      "Parts of Speech",
      "Punctuation and Capitalization",
      "Sentence Structure",
      "Common Errors",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/reading/grammar/thumbnail-4th-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/reading/grammar/grammar_4th5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Two-Step Word Problems With Addition and Subtraction",
      "Multiplication and Division Facts",
      "Round to the Nearest 10 or 100",
      "Measure and Compare Length in Units",
      "Identify Fractions of Shapes and Number Lines",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/all-standards/thumbnail-3rd-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Area and Perimeter of Rectangular Figures",
      "Round to Any Place",
      "Identify Fractions of Shapes and Number Lines",
      "Computation With All Four Operations",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/all-standards/thumbnail-4th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-mixed-math-skills-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "mixed-math-skills",
    standards: [],
    skills: [
      "Multi-Step Word Problems With All Four Operations",
      "Calculate Volume",
      "Decimal Computation With All Four Operations",
      "Add and Subtract Fractions and Mixed Numbers",
      "Identify Lines and Angles",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/all-standards/thumbnail-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/all/math_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-multiplication-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Multiplication Facts",
      "Determine the Unknown Number in an Equation",
      "Word Problems",
      "Properties of Multiplication; Arrays",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/multiplication/preview-3rd-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/multiplication/multiplication_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-multiplication-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "multiplication",
    standards: [],
    skills: [
      "Factors and Multiples",
      "Base Ten Multiplication",
      "Multi-Digit Multiplication",
      "Multiplicative Comparison Word Problems",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/multiplication/preview-4th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/multiplication/multiplication_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-3",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [3],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Fractions on Number Lines",
      "Equivalent Fractions",
      "Fractions as Whole Numbers",
      "Compare Fractions",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/fractions/preview-3rd-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_3rdGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-4",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [4],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Like Denominators",
      "Add and Subtract Mixed Numbers With Like Denominators",
      "Compare Fractions With Different Numerators and Denominators",
      "Multiply Fractions by Whole Numbers",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/fractions/preview-4th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_4thGrade.js",
  },
  {
    id: "yeti-and-the-yams-fractions-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "fractions",
    standards: [],
    skills: [
      "Add and Subtract Fractions With Unlike Denominators",
      "Multiply Fractions and Mixed Numbers",
      "Divide Unit Fractions and Whole Numbers",
      "Fraction Word Problems With All Four Operations",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/fractions/preview-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/fractions/fractions_5thGrade.js",
  },
  {
    id: "yeti-and-the-yams-order-of-operations-5",
    title: "Yeti and the Yams",
    season: "winter",
    grades: [5],
    subject: "math",
    topic: "order-of-operations",
    standards: [],
    skills: [
      "Computation With All Four Operations",
      "Word Problems",
      "Equations With Exponents",
      "Evaluate True or False",
    ],
    thumbnail: "resource/the-yeti-and-the-yam/assets/branding/math/order-of-operations/preview-5th-grade.png",
    path: "resource/the-yeti-and-the-yam/topic/math/order-of-operations/orderOfOperations_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Cupid's Countdown
  // ─────────────────────────────────────────────

  {
    id: "cupids-countdown-mixed-reading-skills-3",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea, Theme, and Supporting Details",
      "Figurative Language",
      "Poetry and Informational Text",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/cupids-countdown/assets/branding/reading/all/preview-3rd-grade.png",
    path: "resource/cupids-countdown/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "cupids-countdown-mixed-reading-skills-4",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea, Theme, and Supporting Details",
      "Figurative Language",
      "Poetry and Informational Text",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/cupids-countdown/assets/branding/reading/all/preview-4th-grade.png",
    path: "resource/cupids-countdown/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "cupids-countdown-mixed-reading-skills-5",
    title: "Cupid's Countdown",
    season: "valentines-day",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Two Main Ideas and Supporting Details",
      "Figurative Language",
      "Poetry and Informational Text",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/cupids-countdown/assets/branding/reading/all/preview-5th-grade.png",
    path: "resource/cupids-countdown/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Rainbow Rescue
  // ─────────────────────────────────────────────

  {
    id: "rainbow-rescue-mixed-reading-skills-3",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Similes and Metaphors",
      "Poetry",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/rainbow-rescue/assets/branding/reading/all/preview-3rd-grade.png",
    path: "resource/rainbow-rescue/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "rainbow-rescue-mixed-reading-skills-4",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Poetry",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/rainbow-rescue/assets/branding/reading/all/preview-4th-grade.png",
    path: "resource/rainbow-rescue/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "rainbow-rescue-mixed-reading-skills-5",
    title: "Rainbow Rescue",
    season: "st-patricks-day",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Poetry",
      "Context Clues",
      "Elements of a Story",
    ],
    thumbnail: "resource/rainbow-rescue/assets/branding/reading/all/preview-5th-grade.png",
    path: "resource/rainbow-rescue/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Eggworld Emergency
  // ─────────────────────────────────────────────

  {
    id: "eggworld-emergency-mixed-reading-skills-3",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Similes and Metaphors",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/eggworld-emergency/assets/branding/reading/all/preview-3rd-grade.png",
    path: "resource/eggworld-emergency/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "eggworld-emergency-mixed-reading-skills-4",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/eggworld-emergency/assets/branding/reading/all/preview-4th-grade.png",
    path: "resource/eggworld-emergency/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "eggworld-emergency-mixed-reading-skills-5",
    title: "Eggworld Emergency",
    season: "easter",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/eggworld-emergency/assets/branding/reading/all/preview-5th-grade.png",
    path: "resource/eggworld-emergency/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Final Bell Breakout
  // ─────────────────────────────────────────────

  {
    id: "final-bell-breakout-mixed-reading-skills-2",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [2],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues and Vocabulary",
      "Text Features",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/final-bell-breakout/assets/branding/reading/all/thumbnail-2nd-grade.png",
    path: "resource/final-bell-breakout/topic/reading/all/reading_2ndGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-3",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues and Vocabulary",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/final-bell-breakout/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/final-bell-breakout/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-4",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/final-bell-breakout/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/final-bell-breakout/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "final-bell-breakout-mixed-reading-skills-5",
    title: "Final Bell Breakout",
    season: "end-of-year",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/final-bell-breakout/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/final-bell-breakout/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Paradise Panic
  // ─────────────────────────────────────────────

  {
    id: "paradise-panic-mixed-reading-skills-3",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Key Details",
      "Story Elements",
      "Context Clues and Vocabulary",
      "Text Structures",
      "Poetry",
    ],
    thumbnail: "resource/paradise-panic/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/paradise-panic/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "paradise-panic-mixed-reading-skills-4",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Story Elements",
      "Context Clues",
      "Figurative Language",
      "Poetry",
    ],
    thumbnail: "resource/paradise-panic/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/paradise-panic/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "paradise-panic-mixed-reading-skills-5",
    title: "Paradise Panic",
    season: "back-to-school",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Story Elements",
      "Context Clues",
      "Figurative Language",
      "Poetry",
    ],
    thumbnail: "resource/paradise-panic/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/paradise-panic/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Funhouse Fright
  // ─────────────────────────────────────────────

  {
    id: "funhouse-fright-mixed-reading-skills-3",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/funhouse-fright/assets/branding/reading/all/preview-3rd-grade.png",
    path: "resource/funhouse-fright/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "funhouse-fright-mixed-reading-skills-4",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/funhouse-fright/assets/branding/reading/all/preview-4th-grade.png",
    path: "resource/funhouse-fright/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "funhouse-fright-mixed-reading-skills-5",
    title: "Funhouse Fright",
    season: "halloween",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Figurative Language",
      "Context Clues",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/funhouse-fright/assets/branding/reading/all/preview-5th-grade.png",
    path: "resource/funhouse-fright/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Turkey Takedown
  // ─────────────────────────────────────────────

  {
    id: "turkey-takedown-mixed-reading-skills-3",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/turkey-takedown/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/turkey-takedown/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "turkey-takedown-mixed-reading-skills-4",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/turkey-takedown/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/turkey-takedown/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "turkey-takedown-mixed-reading-skills-5",
    title: "Turkey Takedown",
    season: "thanksgiving",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Figurative Language",
      "Poetry",
      "Story Elements",
    ],
    thumbnail: "resource/turkey-takedown/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/turkey-takedown/topic/reading/all/reading_5thGrade.js",
  },

  // ─────────────────────────────────────────────
  // Wacky Workshop
  // ─────────────────────────────────────────────

  {
    id: "wacky-workshop-mixed-reading-skills-3",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [3],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Poetry",
      "Figurative Language",
      "Story Elements",
    ],
    thumbnail: "resource/wacky-workshop/assets/branding/reading/all/thumbnail-3rd-grade.png",
    path: "resource/wacky-workshop/topic/reading/all/reading_3rdGrade.js",
  },
  {
    id: "wacky-workshop-mixed-reading-skills-4",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [4],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Poetry",
      "Figurative Language",
      "Story Elements",
    ],
    thumbnail: "resource/wacky-workshop/assets/branding/reading/all/thumbnail-4th-grade.png",
    path: "resource/wacky-workshop/topic/reading/all/reading_4thGrade.js",
  },
  {
    id: "wacky-workshop-mixed-reading-skills-5",
    title: "Wacky Workshop",
    season: "christmas",
    grades: [5],
    subject: "reading",
    topic: "mixed-reading-skills",
    standards: [],
    skills: [
      "Main Idea and Supporting Details",
      "Context Clues",
      "Poetry",
      "Figurative Language",
      "Story Elements",
    ],
    thumbnail: "resource/wacky-workshop/assets/branding/reading/all/thumbnail-5th-grade.png",
    path: "resource/wacky-workshop/topic/reading/all/reading_5thGrade.js",
  },

];
