// Enter the Undermurk! — grade-leveled vocab bank.
// Tier N = Grade N. Each entry: word, definition, distractors (>= 5 for boss rounds).

const undermurkVocab = {
  1: [
    { word: 'happy', definition: 'feeling glad or pleased', distractors: ['sad', 'tired', 'angry', 'hungry', 'sleepy'] },
    { word: 'big', definition: 'large in size', distractors: ['small', 'tiny', 'short', 'thin', 'light'] },
    { word: 'run', definition: 'to move quickly on foot', distractors: ['walk', 'sit', 'sleep', 'eat', 'read'] },
    { word: 'cat', definition: 'a small furry pet that meows', distractors: ['dog', 'bird', 'fish', 'horse', 'cow'] },
    { word: 'red', definition: 'the color of a ripe apple', distractors: ['blue', 'green', 'yellow', 'purple', 'orange'] },
    { word: 'book', definition: 'pages bound together for reading', distractors: ['pen', 'desk', 'chair', 'ball', 'cup'] },
    { word: 'sun', definition: 'the bright star that lights our sky', distractors: ['moon', 'star', 'cloud', 'rain', 'wind'] },
    { word: 'help', definition: 'to give support to someone', distractors: ['hurt', 'hide', 'stop', 'leave', 'break'] },
    { word: 'friend', definition: 'someone you like and trust', distractors: ['enemy', 'stranger', 'teacher', 'parent', 'neighbor'] },
    { word: 'water', definition: 'a clear liquid we drink', distractors: ['milk', 'juice', 'sand', 'rock', 'fire'] },
    { word: 'little', definition: 'small in size', distractors: ['huge', 'giant', 'tall', 'wide', 'heavy'] },
    { word: 'fast', definition: 'moving quickly', distractors: ['slow', 'still', 'late', 'soft', 'quiet'] },
    { word: 'slow', definition: 'moving without much speed', distractors: ['fast', 'quick', 'rapid', 'early', 'loud'] },
    { word: 'cold', definition: 'having a low temperature', distractors: ['hot', 'warm', 'dry', 'bright', 'soft'] },
    { word: 'warm', definition: 'a little hot, but not too hot', distractors: ['cold', 'frozen', 'wet', 'dark', 'hard'] },
    { word: 'jump', definition: 'to push yourself up off the ground', distractors: ['sit', 'crawl', 'sleep', 'read', 'eat'] },
    { word: 'look', definition: 'to use your eyes to see something', distractors: ['listen', 'taste', 'touch', 'sleep', 'talk'] },
    { word: 'smile', definition: 'to make a happy look with your mouth', distractors: ['frown', 'cry', 'yell', 'sleep', 'hide'] },
    { word: 'laugh', definition: 'to make a happy sound when something is funny', distractors: ['cry', 'whisper', 'sleep', 'frown', 'sigh'] },
    { word: 'cry', definition: 'to have tears come from your eyes', distractors: ['laugh', 'smile', 'dance', 'sleep', 'clap'] },
    { word: 'quiet', definition: 'making very little sound', distractors: ['loud', 'noisy', 'wild', 'bright', 'quick'] },
    { word: 'loud', definition: 'making a strong sound', distractors: ['quiet', 'silent', 'soft', 'tiny', 'slow'] },
    { word: 'soft', definition: 'not hard or rough to touch', distractors: ['hard', 'sharp', 'rough', 'heavy', 'loud'] },
    { word: 'hard', definition: 'firm and not easy to bend or press', distractors: ['soft', 'fluffy', 'gentle', 'wet', 'loose'] },
    { word: 'clean', definition: 'not dirty', distractors: ['muddy', 'messy', 'dusty', 'sticky', 'stained'] },
    { word: 'dirty', definition: 'covered with dirt or mess', distractors: ['clean', 'fresh', 'neat', 'washed', 'bright'] },
    { word: 'open', definition: 'not closed or shut', distractors: ['closed', 'locked', 'covered', 'hidden', 'sealed'] },
    { word: 'close', definition: 'to shut something', distractors: ['open', 'lift', 'start', 'throw', 'show'] },
    { word: 'start', definition: 'to begin doing something', distractors: ['finish', 'stop', 'end', 'rest', 'wait'] },
    { word: 'stop', definition: 'to no longer move or continue', distractors: ['start', 'go', 'begin', 'run', 'continue'] },
    { word: 'above', definition: 'in a higher place than something else', distractors: ['below', 'under', 'inside', 'behind', 'beside'] },
    { word: 'below', definition: 'in a lower place than something else', distractors: ['above', 'over', 'outside', 'ahead', 'beside'] },
    { word: 'near', definition: 'not far away', distractors: ['far', 'distant', 'lost', 'high', 'deep'] },
    { word: 'far', definition: 'a long distance away', distractors: ['near', 'close', 'beside', 'inside', 'here'] },
    { word: 'empty', definition: 'having nothing inside', distractors: ['full', 'packed', 'filled', 'heavy', 'crowded'] },
    { word: 'full', definition: 'holding as much as it can', distractors: ['empty', 'bare', 'open', 'tiny', 'broken'] },
    { word: 'day', definition: 'the time when it is usually light outside', distractors: ['night', 'bedtime', 'darkness', 'midnight', 'evening'] },
    { word: 'night', definition: 'the dark part of the day when many people sleep', distractors: ['morning', 'noon', 'day', 'sunrise', 'afternoon'] },
    { word: 'animal', definition: 'a living thing such as a dog, bird, or fish', distractors: ['plant', 'rock', 'chair', 'cloud', 'toy'] },
    { word: 'plant', definition: 'a living thing that usually grows in soil', distractors: ['animal', 'rock', 'table', 'shirt', 'pencil'] },
    { word: 'food', definition: 'something people or animals eat', distractors: ['water', 'air', 'sand', 'soap', 'paper'] },
    { word: 'family', definition: 'people who are related or care for one another as a family', distractors: ['crowd', 'team', 'class', 'strangers', 'audience'] },
    { word: 'school', definition: 'a place where students go to learn', distractors: ['store', 'farm', 'park', 'hospital', 'garage'] },
    { word: 'teacher', definition: 'a person who helps students learn', distractors: ['doctor', 'pilot', 'farmer', 'chef', 'driver'] },
    { word: 'color', definition: 'what makes something look red, blue, green, or another shade', distractors: ['sound', 'smell', 'shape', 'size', 'weight'] },
    { word: 'shape', definition: 'the form or outline of something', distractors: ['color', 'sound', 'taste', 'speed', 'temperature'] },
    { word: 'round', definition: 'shaped like a circle or ball', distractors: ['square', 'flat', 'pointed', 'straight', 'sharp'] },
    { word: 'square', definition: 'a shape with four equal sides', distractors: ['circle', 'triangle', 'oval', 'star', 'heart'] },
    { word: 'first', definition: 'coming before all the others', distractors: ['last', 'second', 'middle', 'later', 'final'] },
    { word: 'last', definition: 'coming after all the others', distractors: ['first', 'early', 'middle', 'next', 'beginning'] },
  ],

  2: [
    { word: 'brave', definition: 'willing to face danger without fear', distractors: ['scared', 'lazy', 'quiet', 'slow', 'weak'] },
    { word: 'garden', definition: 'a place where plants and flowers grow', distractors: ['kitchen', 'bedroom', 'garage', 'office', 'hallway'] },
    { word: 'whisper', definition: 'to speak very softly', distractors: ['shout', 'sing', 'laugh', 'yell', 'scream'] },
    { word: 'gentle', definition: 'soft and kind, not rough', distractors: ['harsh', 'loud', 'sharp', 'heavy', 'fast'] },
    { word: 'shadow', definition: 'a dark shape made when light is blocked', distractors: ['light', 'color', 'sound', 'smell', 'warmth'] },
    { word: 'rescue', definition: 'to save someone from danger', distractors: ['ignore', 'trap', 'lose', 'hide', 'delay'] },
    { word: 'honest', definition: 'telling the truth', distractors: ['sneaky', 'rude', 'lazy', 'noisy', 'selfish'] },
    { word: 'gather', definition: 'to collect things together', distractors: ['scatter', 'drop', 'break', 'throw', 'split'] },
    { word: 'notice', definition: 'to see or become aware of something', distractors: ['forget', 'ignore', 'miss', 'hide', 'deny'] },
    { word: 'protect', definition: 'to keep someone or something safe', distractors: ['harm', 'break', 'leave', 'expose', 'attack'] },
    { word: 'clever', definition: 'quick at learning or solving problems', distractors: ['foolish', 'sleepy', 'slow', 'careless', 'confused'] },
    { word: 'curious', definition: 'wanting to know or learn more', distractors: ['bored', 'certain', 'angry', 'sleepy', 'careless'] },
    { word: 'discover', definition: 'to find or learn something for the first time', distractors: ['lose', 'hide', 'forget', 'cover', 'ignore'] },
    { word: 'imagine', definition: 'to make a picture or idea in your mind', distractors: ['measure', 'forget', 'erase', 'count', 'copy'] },
    { word: 'careful', definition: 'taking time to avoid mistakes or danger', distractors: ['careless', 'reckless', 'rushed', 'wild', 'sloppy'] },
    { word: 'dangerous', definition: 'likely to cause harm or injury', distractors: ['safe', 'gentle', 'harmless', 'calm', 'helpful'] },
    { word: 'sturdy', definition: 'strong and not easily broken', distractors: ['fragile', 'weak', 'flimsy', 'soft', 'loose'] },
    { word: 'vanish', definition: 'to disappear suddenly', distractors: ['appear', 'arrive', 'remain', 'grow', 'shine'] },
    { word: 'arrive', definition: 'to reach a place', distractors: ['leave', 'depart', 'wander', 'return', 'hide'] },
    { word: 'depart', definition: 'to leave a place', distractors: ['arrive', 'enter', 'stay', 'remain', 'visit'] },
    { word: 'repair', definition: 'to fix something that is broken', distractors: ['damage', 'break', 'ruin', 'lose', 'hide'] },
    { word: 'search', definition: 'to look carefully for something', distractors: ['ignore', 'hide', 'lose', 'forget', 'avoid'] },
    { word: 'choose', definition: 'to pick one thing from two or more choices', distractors: ['refuse', 'forget', 'drop', 'mix', 'hide'] },
    { word: 'create', definition: 'to make something new', distractors: ['destroy', 'erase', 'break', 'copy', 'lose'] },
    { word: 'compare', definition: 'to look at things to see how they are alike or different', distractors: ['ignore', 'separate', 'forget', 'hide', 'guess'] },
    { word: 'different', definition: 'not the same', distractors: ['same', 'equal', 'matching', 'identical', 'alike'] },
    { word: 'similar', definition: 'almost the same in some ways', distractors: ['different', 'opposite', 'unrelated', 'separate', 'unequal'] },
    { word: 'remember', definition: 'to keep or bring something back to your mind', distractors: ['forget', 'ignore', 'erase', 'lose', 'miss'] },
    { word: 'explain', definition: 'to make an idea easier to understand', distractors: ['confuse', 'hide', 'deny', 'forget', 'mix'] },
    { word: 'delicious', definition: 'having a very good taste', distractors: ['bitter', 'awful', 'rotten', 'plain', 'sour'] },
    { word: 'enormous', definition: 'very large', distractors: ['tiny', 'little', 'small', 'narrow', 'short'] },
    { word: 'narrow', definition: 'not wide from side to side', distractors: ['wide', 'broad', 'huge', 'open', 'round'] },
    { word: 'wide', definition: 'having a lot of space from side to side', distractors: ['narrow', 'thin', 'tight', 'tiny', 'short'] },
    { word: 'crooked', definition: 'bent or not straight', distractors: ['straight', 'level', 'smooth', 'flat', 'even'] },
    { word: 'smooth', definition: 'even to the touch, without bumps', distractors: ['rough', 'bumpy', 'jagged', 'sharp', 'cracked'] },
    { word: 'rough', definition: 'not smooth; covered with bumps or uneven places', distractors: ['smooth', 'silky', 'even', 'flat', 'soft'] },
    { word: 'bright', definition: 'giving off or filled with a lot of light', distractors: ['dim', 'dark', 'dull', 'shadowy', 'faint'] },
    { word: 'dim', definition: 'not giving off much light', distractors: ['bright', 'shiny', 'glowing', 'sunny', 'clear'] },
    { word: 'lonely', definition: 'sad because you feel alone', distractors: ['cheerful', 'included', 'excited', 'proud', 'grateful'] },
    { word: 'proud', definition: 'pleased with something you did or with someone you care about', distractors: ['ashamed', 'embarrassed', 'disappointed', 'worried', 'jealous'] },
    { word: 'nervous', definition: 'worried or uneasy about what may happen', distractors: ['calm', 'relaxed', 'confident', 'sleepy', 'cheerful'] },
    { word: 'patient', definition: 'able to wait calmly', distractors: ['impatient', 'rushed', 'restless', 'angry', 'wild'] },
    { word: 'selfish', definition: 'caring mostly about what you want', distractors: ['generous', 'helpful', 'kind', 'sharing', 'thoughtful'] },
    { word: 'grateful', definition: 'feeling thankful', distractors: ['ungrateful', 'angry', 'jealous', 'bored', 'worried'] },
    { word: 'puzzled', definition: 'confused because something is hard to understand', distractors: ['certain', 'sure', 'confident', 'calm', 'prepared'] },
  ],

  3: [
    { word: 'ancient', definition: 'very old, from long ago', distractors: ['modern', 'new', 'recent', 'fresh', 'young'] },
    { word: 'journey', definition: 'a trip from one place to another', distractors: ['rest', 'home', 'pause', 'stop', 'delay'] },
    { word: 'courage', definition: 'the strength to do something difficult or scary', distractors: ['fear', 'doubt', 'weakness', 'shame', 'panic'] },
    { word: 'explore', definition: 'to travel through a place to learn about it', distractors: ['avoid', 'ignore', 'destroy', 'abandon', 'forget'] },
    { word: 'decision', definition: 'a choice you make after thinking', distractors: ['accident', 'guess', 'mistake', 'delay', 'confusion'] },
    { word: 'describe', definition: 'to tell what something looks or feels like', distractors: ['hide', 'ignore', 'forget', 'destroy', 'misplace'] },
    { word: 'energy', definition: 'power that lets people and things work or move', distractors: ['silence', 'darkness', 'stillness', 'emptiness', 'weakness'] },
    { word: 'fragile', definition: 'easy to break or damage', distractors: ['strong', 'tough', 'solid', 'heavy', 'thick'] },
    { word: 'neighbor', definition: 'someone who lives near you', distractors: ['stranger', 'visitor', 'enemy', 'leader', 'teacher'] },
    { word: 'precious', definition: 'very valuable or special', distractors: ['cheap', 'useless', 'common', 'broken', 'empty'] },
    { word: 'absorb', definition: 'to take in a liquid, heat, or information', distractors: ['release', 'spill', 'reject', 'scatter', 'reflect'] },
    { word: 'adapt', definition: 'to change so you can fit new conditions', distractors: ['remain', 'refuse', 'freeze', 'repeat', 'ignore'] },
    { word: 'advantage', definition: 'something that gives you a better chance to succeed', distractors: ['disadvantage', 'problem', 'weakness', 'obstacle', 'loss'] },
    { word: 'approach', definition: 'to move closer to something', distractors: ['retreat', 'leave', 'avoid', 'escape', 'depart'] },
    { word: 'astonished', definition: 'very surprised', distractors: ['bored', 'calm', 'uninterested', 'prepared', 'sleepy'] },
    { word: 'attempt', definition: 'to try to do something', distractors: ['refuse', 'quit', 'avoid', 'ignore', 'finish'] },
    { word: 'avoid', definition: 'to stay away from something', distractors: ['approach', 'enter', 'seek', 'follow', 'join'] },
    { word: 'calculate', definition: 'to find an answer using numbers', distractors: ['guess', 'erase', 'draw', 'describe', 'imagine'] },
    { word: 'cause', definition: 'something that makes another thing happen', distractors: ['result', 'ending', 'effect', 'reaction', 'answer'] },
    { word: 'consequence', definition: 'something that happens because of an action', distractors: ['cause', 'plan', 'question', 'choice', 'beginning'] },
    { word: 'contain', definition: 'to hold something inside', distractors: ['release', 'spill', 'scatter', 'empty', 'remove'] },
    { word: 'determine', definition: 'to find out or decide something', distractors: ['ignore', 'wonder', 'forget', 'confuse', 'delay'] },
    { word: 'eager', definition: 'very excited and ready to do something', distractors: ['reluctant', 'bored', 'unwilling', 'sleepy', 'hesitant'] },
    { word: 'effect', definition: 'a change or result caused by something else', distractors: ['cause', 'reason', 'plan', 'question', 'source'] },
    { word: 'examine', definition: 'to look at something closely and carefully', distractors: ['ignore', 'glance', 'hide', 'forget', 'avoid'] },
    { word: 'familiar', definition: 'known because you have seen or experienced it before', distractors: ['strange', 'unknown', 'new', 'mysterious', 'foreign'] },
    { word: 'fortunate', definition: 'having good luck', distractors: ['unlucky', 'unfortunate', 'miserable', 'careless', 'ordinary'] },
    { word: 'gradual', definition: 'happening slowly over time', distractors: ['sudden', 'instant', 'immediate', 'rapid', 'abrupt'] },
    { word: 'identify', definition: 'to recognize or name what something is', distractors: ['confuse', 'hide', 'forget', 'misplace', 'ignore'] },
    { word: 'increase', definition: 'to become greater in size, amount, or number', distractors: ['decrease', 'shrink', 'reduce', 'lessen', 'drop'] },
    { word: 'locate', definition: 'to find the place where something is', distractors: ['lose', 'hide', 'misplace', 'forget', 'remove'] },
    { word: 'ordinary', definition: 'normal or not unusual', distractors: ['rare', 'strange', 'special', 'unusual', 'remarkable'] },
    { word: 'persuade', definition: 'to convince someone to do or believe something', distractors: ['discourage', 'confuse', 'force', 'ignore', 'refuse'] },
    { word: 'prevent', definition: 'to stop something from happening', distractors: ['allow', 'cause', 'encourage', 'begin', 'permit'] },
    { word: 'rare', definition: 'not common or not often found', distractors: ['common', 'usual', 'frequent', 'ordinary', 'plentiful'] },
    { word: 'region', definition: 'a large area of land that is part of a bigger place', distractors: ['object', 'person', 'moment', 'sound', 'number'] },
    { word: 'solution', definition: 'an answer to a problem', distractors: ['problem', 'question', 'mistake', 'obstacle', 'confusion'] },
    { word: 'suitable', definition: 'right or appropriate for a purpose', distractors: ['wrong', 'useless', 'harmful', 'awkward', 'impossible'] },
    { word: 'survive', definition: 'to stay alive or continue through danger or difficulty', distractors: ['fail', 'vanish', 'surrender', 'collapse', 'perish'] },
    { word: 'threaten', definition: 'to show that harm or danger may happen', distractors: ['protect', 'comfort', 'help', 'rescue', 'welcome'] },
  ],

  4: [
    { word: 'analyze', definition: 'to study something carefully to understand it', distractors: ['ignore', 'guess', 'forget', 'destroy', 'hide'] },
    { word: 'contrast', definition: 'to show how two things are different', distractors: ['match', 'copy', 'blend', 'repeat', 'combine'] },
    { word: 'evidence', definition: 'facts or proof that support an idea', distractors: ['opinion', 'rumor', 'guess', 'myth', 'joke'] },
    { word: 'frequent', definition: 'happening often', distractors: ['rare', 'never', 'once', 'seldom', 'occasional'] },
    { word: 'influence', definition: 'the power to change how someone thinks or acts', distractors: ['ignore', 'weaken', 'block', 'remove', 'silence'] },
    { word: 'observe', definition: 'to watch carefully', distractors: ['ignore', 'forget', 'miss', 'disturb', 'interrupt'] },
    { word: 'predict', definition: 'to say what you think will happen', distractors: ['forget', 'deny', 'ignore', 'confuse', 'delay'] },
    { word: 'require', definition: 'to need something', distractors: ['reject', 'avoid', 'refuse', 'skip', 'ignore'] },
    { word: 'summary', definition: 'a short statement of the main points', distractors: ['detail', 'story', 'joke', 'secret', 'error'] },
    { word: 'tradition', definition: 'a custom passed down over time', distractors: ['invention', 'accident', 'surprise', 'mistake', 'novelty'] },
    { word: 'accurate', definition: 'correct and free from mistakes', distractors: ['wrong', 'false', 'careless', 'rough', 'uncertain'] },
    { word: 'achieve', definition: 'to successfully reach a goal', distractors: ['fail', 'abandon', 'lose', 'avoid', 'delay'] },
    { word: 'approximate', definition: 'close to the exact amount but not exact', distractors: ['exact', 'perfect', 'certain', 'identical', 'complete'] },
    { word: 'classify', definition: 'to sort things into groups based on shared features', distractors: ['scatter', 'mix', 'ignore', 'destroy', 'separate randomly'] },
    { word: 'complex', definition: 'made of many connected parts and not simple', distractors: ['simple', 'easy', 'plain', 'basic', 'obvious'] },
    { word: 'consume', definition: 'to use up, eat, or drink something', distractors: ['save', 'store', 'produce', 'protect', 'collect'] },
    { word: 'demonstrate', definition: 'to show clearly how something works or is done', distractors: ['hide', 'confuse', 'deny', 'forget', 'prevent'] },
    { word: 'distribute', definition: 'to give or spread things out among people or places', distractors: ['collect', 'gather', 'hoard', 'hide', 'keep'] },
    { word: 'encounter', definition: 'to meet or come across something unexpectedly', distractors: ['avoid', 'escape', 'ignore', 'miss', 'leave'] },
    { word: 'estimate', definition: 'a careful guess about an amount or value', distractors: ['exact answer', 'proof', 'measurement', 'fact', 'certainty'] },
    { word: 'evaluate', definition: 'to judge the quality, value, or importance of something', distractors: ['ignore', 'copy', 'hide', 'guess', 'repeat'] },
    { word: 'extract', definition: 'to remove or pull something out', distractors: ['insert', 'add', 'attach', 'combine', 'store'] },
    { word: 'flexible', definition: 'able to bend or change easily', distractors: ['rigid', 'stiff', 'fixed', 'brittle', 'solid'] },
    { word: 'indicate', definition: 'to point out or show something', distractors: ['hide', 'deny', 'erase', 'confuse', 'ignore'] },
    { word: 'investigate', definition: 'to examine something to discover facts', distractors: ['ignore', 'assume', 'guess', 'forget', 'avoid'] },
    { word: 'modify', definition: 'to change something slightly', distractors: ['preserve', 'freeze', 'copy', 'ignore', 'destroy completely'] },
    { word: 'organize', definition: 'to arrange things in an orderly way', distractors: ['scatter', 'mix', 'confuse', 'ruin', 'misplace'] },
    { word: 'participate', definition: 'to take part in an activity', distractors: ['watch', 'avoid', 'quit', 'ignore', 'leave'] },
    { word: 'preserve', definition: 'to protect something so it stays in good condition', distractors: ['destroy', 'damage', 'waste', 'abandon', 'erase'] },
    { word: 'process', definition: 'a series of steps used to reach a result', distractors: ['accident', 'shortcut', 'object', 'place', 'opinion'] },
    { word: 'recommend', definition: 'to suggest something as a good choice', distractors: ['forbid', 'reject', 'hide', 'ignore', 'criticize'] },
    { word: 'represent', definition: 'to stand for or show something else', distractors: ['erase', 'hide', 'destroy', 'separate', 'deny'] },
    { word: 'scarce', definition: 'hard to find because there is very little available', distractors: ['abundant', 'plentiful', 'common', 'extra', 'overflowing'] },
    { word: 'specific', definition: 'clearly named or exact rather than general', distractors: ['general', 'vague', 'broad', 'unclear', 'random'] },
    { word: 'temporary', definition: 'lasting only for a limited time', distractors: ['permanent', 'lasting', 'endless', 'fixed', 'eternal'] },
  ],

  5: [
    { word: 'abundant', definition: 'more than enough; plentiful', distractors: ['scarce', 'rare', 'empty', 'limited', 'tiny'] },
    { word: 'benefit', definition: 'something good that helps you', distractors: ['harm', 'loss', 'problem', 'cost', 'risk'] },
    { word: 'consider', definition: 'to think about carefully', distractors: ['ignore', 'reject', 'forget', 'rush', 'dismiss'] },
    { word: 'decline', definition: 'to become smaller, weaker, or fewer', distractors: ['grow', 'rise', 'increase', 'expand', 'surge'] },
    { word: 'essential', definition: 'absolutely necessary', distractors: ['optional', 'extra', 'useless', 'minor', 'trivial'] },
    { word: 'factor', definition: 'something that affects a result', distractors: ['accident', 'coincidence', 'mistake', 'joke', 'guess'] },
    { word: 'maintain', definition: 'to keep something in good condition', distractors: ['break', 'neglect', 'abandon', 'destroy', 'ruin'] },
    { word: 'occur', definition: 'to happen', distractors: ['vanish', 'stop', 'fail', 'pause', 'disappear'] },
    { word: 'prior', definition: 'coming before in time or order', distractors: ['later', 'next', 'future', 'final', 'recent'] },
    { word: 'significant', definition: 'important or meaningful', distractors: ['minor', 'trivial', 'small', 'useless', 'random'] },
    { word: 'acknowledge', definition: 'to admit, recognize, or show that you are aware of something', distractors: ['deny', 'ignore', 'hide', 'forget', 'reject'] },
    { word: 'alternative', definition: 'another choice or possibility', distractors: ['requirement', 'result', 'rule', 'fact', 'problem'] },
    { word: 'anticipate', definition: 'to expect something before it happens', distractors: ['forget', 'doubt', 'ignore', 'remember afterward', 'prevent'] },
    { word: 'apparent', definition: 'easy to notice or understand; seeming to be true', distractors: ['hidden', 'unclear', 'secret', 'impossible', 'invisible'] },
    { word: 'circumstance', definition: 'a condition or fact that affects a situation', distractors: ['solution', 'object', 'opinion', 'measurement', 'location'] },
    { word: 'contradict', definition: 'to say the opposite of what someone or something states', distractors: ['agree', 'confirm', 'support', 'repeat', 'accept'] },
    { word: 'critical', definition: 'very important to the success or outcome of something', distractors: ['minor', 'optional', 'trivial', 'unrelated', 'ordinary'] },
    { word: 'diminish', definition: 'to make or become smaller or less', distractors: ['increase', 'expand', 'strengthen', 'multiply', 'enlarge'] },
    { word: 'elaborate', definition: 'to add more details or explain more fully', distractors: ['shorten', 'hide', 'simplify', 'erase', 'ignore'] },
    { word: 'emerge', definition: 'to come out, appear, or become known', distractors: ['vanish', 'hide', 'sink', 'disappear', 'retreat'] },
    { word: 'emphasize', definition: 'to give special importance or attention to something', distractors: ['ignore', 'minimize', 'hide', 'weaken', 'dismiss'] },
    { word: 'generate', definition: 'to produce or create something', distractors: ['destroy', 'remove', 'consume', 'lose', 'prevent'] },
    { word: 'illustrate', definition: 'to explain or make something clear with examples or pictures', distractors: ['confuse', 'hide', 'deny', 'erase', 'complicate'] },
    { word: 'impact', definition: 'a strong effect or influence', distractors: ['cause', 'detail', 'guess', 'silence', 'absence'] },
    { word: 'justify', definition: 'to give reasons or evidence that support a choice or idea', distractors: ['deny', 'guess', 'hide', 'contradict', 'ignore'] },
    { word: 'principle', definition: 'a basic rule, belief, or idea that guides actions', distractors: ['accident', 'rumor', 'exception', 'object', 'mistake'] },
    { word: 'resist', definition: 'to oppose or refuse to give in to something', distractors: ['accept', 'surrender', 'allow', 'welcome', 'obey'] },
    { word: 'transform', definition: 'to change greatly in form or appearance', distractors: ['preserve', 'maintain', 'freeze', 'repeat', 'restore'] },
    { word: 'widespread', definition: 'existing or happening over a large area or among many people', distractors: ['rare', 'local', 'limited', 'isolated', 'narrow'] },
    { word: 'reluctant', definition: 'not willing or eager to do something', distractors: ['eager', 'willing', 'excited', 'ready', 'enthusiastic'] },
  ],

  6: [
    { word: 'accumulate', definition: 'to gather or collect over time', distractors: ['scatter', 'lose', 'waste', 'drain', 'reduce'] },
    { word: 'conclude', definition: 'to decide after thinking about evidence', distractors: ['begin', 'guess', 'wonder', 'delay', 'confuse'] },
    { word: 'distinct', definition: 'clearly different or separate', distractors: ['similar', 'identical', 'mixed', 'vague', 'blended'] },
    { word: 'establish', definition: 'to set up or create something that lasts', distractors: ['destroy', 'remove', 'cancel', 'abandon', 'break'] },
    { word: 'interpret', definition: 'to explain the meaning of something', distractors: ['ignore', 'misread', 'confuse', 'hide', 'forget'] },
    { word: 'method', definition: 'a planned way of doing something', distractors: ['accident', 'chaos', 'guess', 'luck', 'surprise'] },
    { word: 'potential', definition: 'possible ability that may develop in the future', distractors: ['failure', 'weakness', 'limit', 'end', 'loss'] },
    { word: 'relevant', definition: 'connected to what is being discussed', distractors: ['random', 'unrelated', 'useless', 'confusing', 'distant'] },
    { word: 'structure', definition: 'the way parts are arranged or built', distractors: ['chaos', 'mess', 'ruin', 'gap', 'void'] },
    { word: 'transfer', definition: 'to move from one place to another', distractors: ['keep', 'hold', 'store', 'block', 'trap'] },
    { word: 'articulate', definition: 'to express an idea clearly and effectively', distractors: ['mumble', 'confuse', 'conceal', 'misstate', 'silence'] },
    { word: 'compile', definition: 'to collect information from different sources into one place', distractors: ['scatter', 'discard', 'separate', 'erase', 'destroy'] },
    { word: 'comprehensive', definition: 'including nearly all important parts or details', distractors: ['partial', 'limited', 'incomplete', 'narrow', 'brief'] },
    { word: 'conventional', definition: 'following what is commonly or traditionally done', distractors: ['unusual', 'experimental', 'original', 'rebellious', 'unexpected'] },
    { word: 'criteria', definition: 'standards used to judge or decide something', distractors: ['results', 'opinions', 'accidents', 'examples', 'questions'] },
    { word: 'deduce', definition: 'to reach a conclusion by using facts and reasoning', distractors: ['guess', 'assume', 'forget', 'ignore', 'invent'] },
    { word: 'differentiate', definition: 'to recognize or show the differences between things', distractors: ['combine', 'confuse', 'match', 'merge', 'equalize'] },
    { word: 'facilitate', definition: 'to make a process or action easier', distractors: ['hinder', 'block', 'delay', 'complicate', 'prevent'] },
    { word: 'formulate', definition: 'to develop an idea or plan carefully', distractors: ['abandon', 'erase', 'ignore', 'destroy', 'improvise blindly'] },
    { word: 'infer', definition: 'to reach an idea or conclusion from evidence rather than direct statements', distractors: ['observe directly', 'quote', 'prove', 'announce', 'memorize'] },
    { word: 'isolate', definition: 'to separate something from everything around it', distractors: ['combine', 'connect', 'merge', 'gather', 'include'] },
    { word: 'objective', definition: 'based on facts rather than personal feelings', distractors: ['biased', 'emotional', 'personal', 'subjective', 'prejudiced'] },
    { word: 'reinforce', definition: 'to strengthen or support something', distractors: ['weaken', 'undermine', 'damage', 'remove', 'oppose'] },
    { word: 'subsequent', definition: 'coming after something else in time or order', distractors: ['prior', 'earlier', 'previous', 'initial', 'first'] },
    { word: 'transition', definition: 'a change from one state, stage, or condition to another', distractors: ['stability', 'pause', 'repetition', 'ending', 'barrier'] },
  ],

  7: [
    { word: 'ambiguous', definition: 'having more than one possible meaning', distractors: ['clear', 'obvious', 'exact', 'certain', 'precise'] },
    { word: 'compensate', definition: 'to make up for a loss or mistake', distractors: ['ignore', 'worsen', 'neglect', 'refuse', 'avoid'] },
    { word: 'contribute', definition: 'to give something to help achieve a goal', distractors: ['withhold', 'steal', 'block', 'remove', 'hinder'] },
    { word: 'derive', definition: 'to obtain something from a source', distractors: ['lose', 'destroy', 'reject', 'ignore', 'waste'] },
    { word: 'equivalent', definition: 'equal in value, amount, or meaning', distractors: ['different', 'opposite', 'lesser', 'unrelated', 'weaker'] },
    { word: 'hypothesis', definition: 'a testable idea that may explain an observation', distractors: ['proof', 'fact', 'law', 'guess', 'joke'] },
    { word: 'imply', definition: 'to suggest something without stating it directly', distractors: ['deny', 'state', 'prove', 'ignore', 'confess'] },
    { word: 'perspective', definition: 'a point of view or way of seeing things', distractors: ['fact', 'object', 'rule', 'tool', 'number'] },
    { word: 'proportion', definition: 'a part compared to the whole', distractors: ['whole', 'total', 'sum', 'limit', 'edge'] },
    { word: 'sequence', definition: 'an ordered list of events or steps', distractors: ['random', 'chaos', 'mix', 'pause', 'gap'] },
    { word: 'ascertain', definition: 'to find out something with certainty', distractors: ['guess', 'wonder', 'assume', 'ignore', 'misunderstand'] },
    { word: 'compatible', definition: 'able to exist or work together without conflict', distractors: ['incompatible', 'conflicting', 'opposed', 'unrelated', 'mismatched'] },
    { word: 'constrain', definition: 'to limit or restrict what can happen', distractors: ['free', 'expand', 'encourage', 'release', 'enable'] },
    { word: 'empirical', definition: 'based on observation or experiment rather than only theory', distractors: ['imaginary', 'theoretical', 'speculative', 'assumed', 'fictional'] },
    { word: 'inevitable', definition: 'certain to happen and impossible to avoid', distractors: ['avoidable', 'unlikely', 'optional', 'uncertain', 'preventable'] },
    { word: 'intrinsic', definition: 'belonging naturally to something as an essential quality', distractors: ['external', 'added', 'temporary', 'borrowed', 'accidental'] },
    { word: 'manipulate', definition: 'to control or change something skillfully, sometimes unfairly', distractors: ['ignore', 'release', 'observe', 'abandon', 'accept'] },
    { word: 'prevalent', definition: 'common or widespread in a particular place or time', distractors: ['rare', 'scarce', 'unusual', 'isolated', 'absent'] },
    { word: 'rational', definition: 'based on reason and logical thinking', distractors: ['irrational', 'emotional', 'random', 'reckless', 'illogical'] },
    { word: 'scrutinize', definition: 'to examine something very closely and carefully', distractors: ['glance', 'ignore', 'overlook', 'skim', 'dismiss'] },
  ],

  8: [
    { word: 'advocate', definition: 'to publicly support a cause or idea', distractors: ['oppose', 'reject', 'ignore', 'attack', 'abandon'] },
    { word: 'bias', definition: 'an unfair preference for or against something', distractors: ['fairness', 'balance', 'truth', 'proof', 'neutrality'] },
    { word: 'coherent', definition: 'logical and easy to follow', distractors: ['confusing', 'random', 'broken', 'vague', 'messy'] },
    { word: 'diverse', definition: 'showing a great deal of variety', distractors: ['uniform', 'identical', 'narrow', 'limited', 'same'] },
    { word: 'explicit', definition: 'stated clearly and directly', distractors: ['hidden', 'vague', 'implied', 'secret', 'unclear'] },
    { word: 'integrate', definition: 'to combine parts into a whole', distractors: ['separate', 'split', 'remove', 'isolate', 'break'] },
    { word: 'paraphrase', definition: 'to restate something in different words', distractors: ['quote', 'copy', 'ignore', 'delete', 'misquote'] },
    { word: 'preliminary', definition: 'coming before the main event', distractors: ['final', 'last', 'complete', 'main', 'ultimate'] },
    { word: 'refute', definition: 'to prove a statement is wrong', distractors: ['support', 'confirm', 'accept', 'praise', 'ignore'] },
    { word: 'sustain', definition: 'to keep something going over time', distractors: ['stop', 'end', 'break', 'abandon', 'weaken'] },
    { word: 'anomaly', definition: 'something that differs from what is normal or expected', distractors: ['pattern', 'standard', 'rule', 'average', 'routine'] },
    { word: 'contentious', definition: 'likely to cause disagreement or argument', distractors: ['peaceful', 'uncontroversial', 'agreeable', 'settled', 'harmonious'] },
    { word: 'discrepancy', definition: 'a difference between things that should match', distractors: ['agreement', 'match', 'consistency', 'similarity', 'balance'] },
    { word: 'exacerbate', definition: 'to make a problem or bad situation worse', distractors: ['improve', 'relieve', 'reduce', 'solve', 'ease'] },
    { word: 'ubiquitous', definition: 'present or appearing almost everywhere', distractors: ['rare', 'scarce', 'hidden', 'local', 'isolated'] },
  ],

  9: [
    { word: 'arbitrary', definition: 'based on random choice rather than reason', distractors: ['logical', 'planned', 'fair', 'reasoned', 'systematic'] },
    { word: 'connotation', definition: 'a feeling or idea suggested by a word', distractors: ['definition', 'spelling', 'sound', 'grammar', 'syllable'] },
    { word: 'corroborate', definition: 'to confirm with supporting evidence', distractors: ['deny', 'refute', 'weaken', 'contradict', 'ignore'] },
    { word: 'diligent', definition: 'careful and steady in work or effort', distractors: ['lazy', 'careless', 'hasty', 'sloppy', 'idle'] },
    { word: 'eloquent', definition: 'fluent and persuasive in speaking or writing', distractors: ['silent', 'awkward', 'confused', 'rude', 'mumbled'] },
    { word: 'inherent', definition: 'existing as a permanent essential quality', distractors: ['temporary', 'external', 'optional', 'added', 'borrowed'] },
    { word: 'mitigate', definition: 'to make something less severe', distractors: ['worsen', 'increase', 'cause', 'ignore', 'provoke'] },
    { word: 'nuance', definition: 'a subtle difference in meaning or tone', distractors: ['obvious', 'clarity', 'simplicity', 'sameness', 'uniformity'] },
    { word: 'pragmatic', definition: 'dealing with things sensibly and realistically', distractors: ['idealistic', 'impractical', 'foolish', 'random', 'careless'] },
    { word: 'substantiate', definition: 'to provide evidence to support a claim', distractors: ['deny', 'weaken', 'ignore', 'guess', 'fabricate'] },
  ],

  10: [
    { word: 'abstruse', definition: 'difficult to understand', distractors: ['simple', 'clear', 'obvious', 'plain', 'easy'] },
    { word: 'acquiesce', definition: 'to accept something reluctantly but without protest', distractors: ['refuse', 'resist', 'reject', 'fight', 'deny'] },
    { word: 'capricious', definition: 'given to sudden changes of mood or mind', distractors: ['steady', 'predictable', 'constant', 'stable', 'reliable'] },
    { word: 'demagogue', definition: 'a leader who manipulates people with emotion', distractors: ['servant', 'scholar', 'engineer', 'artist', 'farmer'] },
    { word: 'ephemeral', definition: 'lasting for a very short time', distractors: ['permanent', 'endless', 'eternal', 'lasting', 'fixed'] },
    { word: 'fastidious', definition: 'very attentive to accuracy and detail', distractors: ['careless', 'sloppy', 'casual', 'lazy', 'reckless'] },
    { word: 'iconoclast', definition: 'someone who challenges accepted beliefs', distractors: ['follower', 'conformist', 'traditionalist', 'imitator', 'bystander'] },
    { word: 'juxtapose', definition: 'to place two things side by side for contrast', distractors: ['separate', 'hide', 'merge', 'scatter', 'isolate'] },
    { word: 'obfuscate', definition: 'to make something unclear or confusing', distractors: ['clarify', 'explain', 'simplify', 'reveal', 'illuminate'] },
    { word: 'perfunctory', definition: 'done with little interest or effort', distractors: ['careful', 'thorough', 'passionate', 'detailed', 'eager'] },
  ],
};