// Enter the Undermurk! — grade-leveled vocab bank.
// Tier N = Grade N. Each entry: word, definition, distractors (>= 5 for boss rounds).
// Expand toward 500+ words without changing the schema.

const undermurkVocab = {
  1: [
    { word: 'happy', definition: 'feeling glad or pleased', distractors: ['sad', 'tired', 'angry', 'hungry', 'sleepy'] },
    { word: 'big', definition: 'large in size', distractors: ['small', 'tiny', 'short', 'thin', 'light'] },
    { word: 'run', definition: 'to move quickly on foot', distractors: ['walk', 'sit', 'sleep', 'eat', 'read'] },
    { word: 'cat', definition: 'a small furry pet that meows', distractors: ['dog', 'bird', 'fish', 'horse', 'cow'] },
    { word: 'red', definition: 'the color of a ripe apple', distractors: ['blue', 'green', 'yellow', 'purple', 'orange'] },
    { word: 'book', definition: 'pages bound together for reading', distractors: ['pen', 'desk', 'chair', 'ball', 'cup'] },
    { word: 'sun', definition: 'the bright star that lights our sky', distractors: ['moon', 'star', 'cloud', 'rain', 'wind'] },
    { word: 'help', definition: 'to give support to someone', distractors: ['hurt', 'hide', 'stop', 'leave', 'break'] },
    { word: 'friend', definition: 'someone you like and trust', distractors: ['enemy', 'stranger', 'teacher', 'parent', 'neighbor'] },
    { word: 'water', definition: 'a clear liquid we drink', distractors: ['milk', 'juice', 'sand', 'rock', 'fire'] },
    { word: 'play', definition: 'to have fun in a game or activity', distractors: ['work', 'sleep', 'cry', 'study', 'clean'] },
    { word: 'home', definition: 'the place where you live', distractors: ['school', 'store', 'park', 'road', 'field'] },
  ],
  2: [
    { word: 'brave', definition: 'willing to face danger without fear', distractors: ['scared', 'lazy', 'quiet', 'slow', 'weak'] },
    { word: 'garden', definition: 'a place where plants and flowers grow', distractors: ['kitchen', 'bedroom', 'garage', 'office', 'hallway'] },
    { word: 'whisper', definition: 'to speak very softly', distractors: ['shout', 'sing', 'laugh', 'yell', 'scream'] },
    { word: 'gentle', definition: 'soft and kind, not rough', distractors: ['harsh', 'loud', 'sharp', 'heavy', 'fast'] },
    { word: 'shadow', definition: 'a dark shape made when light is blocked', distractors: ['light', 'color', 'sound', 'smell', 'warmth'] },
    { word: 'rescue', definition: 'to save someone from danger', distractors: ['ignore', 'trap', 'lose', 'hide', 'delay'] },
    { word: 'honest', definition: 'telling the truth', distractors: ['sneaky', 'rude', 'lazy', 'noisy', 'selfish'] },
    { word: 'gather', definition: 'to collect things together', distractors: ['scatter', 'drop', 'break', 'throw', 'split'] },
    { word: 'notice', definition: 'to see or become aware of something', distractors: ['forget', 'ignore', 'miss', 'hide', 'deny'] },
    { word: 'protect', definition: 'to keep someone or something safe', distractors: ['harm', 'break', 'leave', 'expose', 'attack'] },
    { word: 'wonder', definition: 'to feel curious about something', distractors: ['know', 'ignore', 'forget', 'decide', 'complain'] },
    { word: 'peaceful', definition: 'calm and free from noise or trouble', distractors: ['noisy', 'wild', 'angry', 'busy', 'chaotic'] },
  ],
  3: [
    { word: 'ancient', definition: 'very old, from long ago', distractors: ['modern', 'new', 'recent', 'fresh', 'young'] },
    { word: 'journey', definition: 'a trip from one place to another', distractors: ['rest', 'home', 'pause', 'stop', 'delay'] },
    { word: 'courage', definition: 'the strength to do something difficult or scary', distractors: ['fear', 'doubt', 'weakness', 'shame', 'panic'] },
    { word: 'explore', definition: 'to travel through a place to learn about it', distractors: ['avoid', 'ignore', 'destroy', 'abandon', 'forget'] },
    { word: 'decision', definition: 'a choice you make after thinking', distractors: ['accident', 'guess', 'mistake', 'delay', 'confusion'] },
    { word: 'describe', definition: 'to tell what something looks or feels like', distractors: ['hide', 'ignore', 'forget', 'destroy', 'misplace'] },
    { word: 'energy', definition: 'power that lets people and things work or move', distractors: ['silence', 'darkness', 'stillness', 'emptiness', 'weakness'] },
    { word: 'fragile', definition: 'easy to break or damage', distractors: ['strong', 'tough', 'solid', 'heavy', 'thick'] },
    { word: 'neighbor', definition: 'someone who lives near you', distractors: ['stranger', 'visitor', 'enemy', 'leader', 'teacher'] },
    { word: 'precious', definition: 'very valuable or special', distractors: ['cheap', 'useless', 'common', 'broken', 'empty'] },
    { word: 'shelter', definition: 'a place that protects you from weather or danger', distractors: ['storm', 'danger', 'exposure', 'wilderness', 'attack'] },
    { word: 'voyage', definition: 'a long trip, often by sea or space', distractors: ['rest', 'nap', 'pause', 'stay', 'return'] },
  ],
  4: [
    { word: 'analyze', definition: 'to study something carefully to understand it', distractors: ['ignore', 'guess', 'forget', 'destroy', 'hide'] },
    { word: 'contrast', definition: 'to show how two things are different', distractors: ['match', 'copy', 'blend', 'repeat', 'combine'] },
    { word: 'evidence', definition: 'facts or proof that support an idea', distractors: ['opinion', 'rumor', 'guess', 'myth', 'joke'] },
    { word: 'frequent', definition: 'happening often', distractors: ['rare', 'never', 'once', 'seldom', 'occasional'] },
    { word: 'influence', definition: 'the power to change how someone thinks or acts', distractors: ['ignore', 'weaken', 'block', 'remove', 'silence'] },
    { word: 'observe', definition: 'to watch carefully', distractors: ['ignore', 'forget', 'miss', 'disturb', 'interrupt'] },
    { word: 'predict', definition: 'to say what you think will happen', distractors: ['forget', 'deny', 'ignore', 'confuse', 'delay'] },
    { word: 'require', definition: 'to need something', distractors: ['reject', 'avoid', 'refuse', 'skip', 'ignore'] },
    { word: 'summary', definition: 'a short statement of the main points', distractors: ['detail', 'story', 'joke', 'secret', 'error'] },
    { word: 'tradition', definition: 'a custom passed down over time', distractors: ['invention', 'accident', 'surprise', 'mistake', 'novelty'] },
    { word: 'urgent', definition: 'needing immediate attention', distractors: ['optional', 'slow', 'casual', 'minor', 'delayed'] },
    { word: 'visible', definition: 'able to be seen', distractors: ['hidden', 'invisible', 'buried', 'lost', 'forgotten'] },
  ],
  5: [
    { word: 'abundant', definition: 'more than enough; plentiful', distractors: ['scarce', 'rare', 'empty', 'limited', 'tiny'] },
    { word: 'benefit', definition: 'something good that helps you', distractors: ['harm', 'loss', 'problem', 'cost', 'risk'] },
    { word: 'consider', definition: 'to think about carefully', distractors: ['ignore', 'reject', 'forget', 'rush', 'dismiss'] },
    { word: 'decline', definition: 'to become smaller, weaker, or fewer', distractors: ['grow', 'rise', 'increase', 'expand', 'surge'] },
    { word: 'essential', definition: 'absolutely necessary', distractors: ['optional', 'extra', 'useless', 'minor', 'trivial'] },
    { word: 'factor', definition: 'something that affects a result', distractors: ['accident', 'coincidence', 'mistake', 'joke', 'guess'] },
    { word: 'maintain', definition: 'to keep something in good condition', distractors: ['break', 'neglect', 'abandon', 'destroy', 'ruin'] },
    { word: 'occur', definition: 'to happen', distractors: ['vanish', 'stop', 'fail', 'pause', 'disappear'] },
    { word: 'prior', definition: 'coming before in time or order', distractors: ['later', 'next', 'future', 'final', 'recent'] },
    { word: 'significant', definition: 'important or meaningful', distractors: ['minor', 'trivial', 'small', 'useless', 'random'] },
    { word: 'theory', definition: 'an idea that explains why something happens', distractors: ['fact', 'proof', 'joke', 'guess', 'accident'] },
    { word: 'vary', definition: 'to change or be different', distractors: ['match', 'repeat', 'stay', 'fix', 'freeze'] },
  ],
  6: [
    { word: 'accumulate', definition: 'to gather or collect over time', distractors: ['scatter', 'lose', 'waste', 'drain', 'reduce'] },
    { word: 'conclude', definition: 'to decide after thinking about evidence', distractors: ['begin', 'guess', 'wonder', 'delay', 'confuse'] },
    { word: 'distinct', definition: 'clearly different or separate', distractors: ['similar', 'identical', 'mixed', 'vague', 'blended'] },
    { word: 'establish', definition: 'to set up or create something that lasts', distractors: ['destroy', 'remove', 'cancel', 'abandon', 'break'] },
    { word: 'interpret', definition: 'to explain the meaning of something', distractors: ['ignore', 'misread', 'confuse', 'hide', 'forget'] },
    { word: 'method', definition: 'a planned way of doing something', distractors: ['accident', 'chaos', 'guess', 'luck', 'surprise'] },
    { word: 'potential', definition: 'possible ability that may develop in the future', distractors: ['failure', 'weakness', 'limit', 'end', 'loss'] },
    { word: 'relevant', definition: 'connected to what is being discussed', distractors: ['random', 'unrelated', 'useless', 'confusing', 'distant'] },
    { word: 'structure', definition: 'the way parts are arranged or built', distractors: ['chaos', 'mess', 'ruin', 'gap', 'void'] },
    { word: 'transfer', definition: 'to move from one place to another', distractors: ['keep', 'hold', 'store', 'block', 'trap'] },
    { word: 'valid', definition: 'based on truth or good reasoning', distractors: ['false', 'wrong', 'fake', 'invalid', 'absurd'] },
    { word: 'volume', definition: 'the amount of space something takes up', distractors: ['weight', 'color', 'sound', 'speed', 'time'] },
  ],
  7: [
    { word: 'ambiguous', definition: 'having more than one possible meaning', distractors: ['clear', 'obvious', 'exact', 'certain', 'precise'] },
    { word: 'compensate', definition: 'to make up for a loss or mistake', distractors: ['ignore', 'worsen', 'neglect', 'refuse', 'avoid'] },
    { word: 'contribute', definition: 'to give something to help achieve a goal', distractors: ['withhold', 'steal', 'block', 'remove', 'hinder'] },
    { word: 'derive', definition: 'to obtain something from a source', distractors: ['lose', 'destroy', 'reject', 'ignore', 'waste'] },
    { word: 'equivalent', definition: 'equal in value, amount, or meaning', distractors: ['different', 'opposite', 'lesser', 'unrelated', 'weaker'] },
    { word: 'hypothesis', definition: 'a testable idea that may explain an observation', distractors: ['proof', 'fact', 'law', 'guess', 'joke'] },
    { word: 'imply', definition: 'to suggest something without stating it directly', distractors: ['deny', 'state', 'prove', 'ignore', 'confess'] },
    { word: 'perspective', definition: 'a point of view or way of seeing things', distractors: ['fact', 'object', 'rule', 'tool', 'number'] },
    { word: 'proportion', definition: 'a part compared to the whole', distractors: ['whole', 'total', 'sum', 'limit', 'edge'] },
    { word: 'sequence', definition: 'an ordered list of events or steps', distractors: ['random', 'chaos', 'mix', 'pause', 'gap'] },
    { word: 'symbolize', definition: 'to represent an idea through a symbol', distractors: ['hide', 'deny', 'break', 'ignore', 'confuse'] },
    { word: 'underlie', definition: 'to form the basis of something', distractors: ['cover', 'hide', 'block', 'remove', 'replace'] },
  ],
  8: [
    { word: 'advocate', definition: 'to publicly support a cause or idea', distractors: ['oppose', 'reject', 'ignore', 'attack', 'abandon'] },
    { word: 'bias', definition: 'an unfair preference for or against something', distractors: ['fairness', 'balance', 'truth', 'proof', 'neutrality'] },
    { word: 'coherent', definition: 'logical and easy to follow', distractors: ['confusing', 'random', 'broken', 'vague', 'messy'] },
    { word: 'diverse', definition: 'showing a great deal of variety', distractors: ['uniform', 'identical', 'narrow', 'limited', 'same'] },
    { word: 'explicit', definition: 'stated clearly and directly', distractors: ['hidden', 'vague', 'implied', 'secret', 'unclear'] },
    { word: 'integrate', definition: 'to combine parts into a whole', distractors: ['separate', 'split', 'remove', 'isolate', 'break'] },
    { word: 'paraphrase', definition: 'to restate something in different words', distractors: ['quote', 'copy', 'ignore', 'delete', 'misquote'] },
    { word: 'preliminary', definition: 'coming before the main event', distractors: ['final', 'last', 'complete', 'main', 'ultimate'] },
    { word: 'refute', definition: 'to prove a statement is wrong', distractors: ['support', 'confirm', 'accept', 'praise', 'ignore'] },
    { word: 'sustain', definition: 'to keep something going over time', distractors: ['stop', 'end', 'break', 'abandon', 'weaken'] },
    { word: 'tentative', definition: 'not certain or fixed yet', distractors: ['final', 'certain', 'sure', 'fixed', 'decided'] },
    { word: 'verify', definition: 'to check that something is true or accurate', distractors: ['guess', 'assume', 'deny', 'ignore', 'fabricate'] },
  ],
  9: [
    { word: 'arbitrary', definition: 'based on random choice rather than reason', distractors: ['logical', 'planned', 'fair', 'reasoned', 'systematic'] },
    { word: 'connotation', definition: 'a feeling or idea suggested by a word', distractors: ['definition', 'spelling', 'sound', 'grammar', 'syllable'] },
    { word: 'corroborate', definition: 'to confirm with supporting evidence', distractors: ['deny', 'refute', 'weaken', 'contradict', 'ignore'] },
    { word: 'diligent', definition: 'careful and steady in work or effort', distractors: ['lazy', 'careless', 'hasty', 'sloppy', 'idle'] },
    { word: 'eloquent', definition: 'fluent and persuasive in speaking or writing', distractors: ['silent', 'awkward', 'confused', 'rude', 'mumbled'] },
    { word: 'inherent', definition: 'existing as a permanent essential quality', distractors: ['temporary', 'external', 'optional', 'added', 'borrowed'] },
    { word: 'mitigate', definition: 'to make something less severe', distractors: ['worsen', 'increase', 'cause', 'ignore', 'provoke'] },
    { word: 'nuance', definition: 'a subtle difference in meaning or tone', distractors: ['obvious', 'clarity', 'simplicity', 'sameness', 'uniformity'] },
    { word: 'pragmatic', definition: 'dealing with things sensibly and realistically', distractors: ['idealistic', 'impractical', 'foolish', 'random', 'careless'] },
    { word: 'substantiate', definition: 'to provide evidence to support a claim', distractors: ['deny', 'weaken', 'ignore', 'guess', 'fabricate'] },
    { word: 'synthesis', definition: 'combining ideas to form a new whole', distractors: ['division', 'separation', 'destruction', 'reduction', 'isolation'] },
    { word: 'undermine', definition: 'to weaken gradually or secretly', distractors: ['support', 'strengthen', 'build', 'praise', 'reinforce'] },
  ],
  10: [
    { word: 'abstruse', definition: 'difficult to understand', distractors: ['simple', 'clear', 'obvious', 'plain', 'easy'] },
    { word: 'acquiesce', definition: 'to accept something reluctantly but without protest', distractors: ['refuse', 'resist', 'reject', 'fight', 'deny'] },
    { word: 'capricious', definition: 'given to sudden changes of mood or mind', distractors: ['steady', 'predictable', 'constant', 'stable', 'reliable'] },
    { word: 'demagogue', definition: 'a leader who manipulates people with emotion', distractors: ['servant', 'scholar', 'engineer', 'artist', 'farmer'] },
    { word: 'ephemeral', definition: 'lasting for a very short time', distractors: ['permanent', 'endless', 'eternal', 'lasting', 'fixed'] },
    { word: 'fastidious', definition: 'very attentive to accuracy and detail', distractors: ['careless', 'sloppy', 'casual', 'lazy', 'reckless'] },
    { word: 'iconoclast', definition: 'someone who challenges accepted beliefs', distractors: ['follower', 'conformist', 'traditionalist', 'imitator', 'bystander'] },
    { word: 'juxtapose', definition: 'to place two things side by side for contrast', distractors: ['separate', 'hide', 'merge', 'scatter', 'isolate'] },
    { word: 'obfuscate', definition: 'to make something unclear or confusing', distractors: ['clarify', 'explain', 'simplify', 'reveal', 'illuminate'] },
    { word: 'perfunctory', definition: 'done with little interest or effort', distractors: ['careful', 'thorough', 'passionate', 'detailed', 'eager'] },
    { word: 'recalcitrant', definition: 'stubbornly refusing to obey', distractors: ['obedient', 'compliant', 'willing', 'cooperative', 'docile'] },
    { word: 'vicarious', definition: 'experienced through another person rather than directly', distractors: ['direct', 'personal', 'actual', 'immediate', 'physical'] },
  ],
};
