// Enter the Undermurk! — grade-leveled vocab bank.
// Tier N = Grade N. Each entry: word, definition, distractors (>= 5 for boss rounds).

const undermurkVocab = {
  1: [
    { word: 'happy', definition: 'feeling glad or pleased', distractors: ['sad', 'tired', 'angry', 'hungry', 'sleepy'] },
    { word: 'big', definition: 'large in size', distractors: ['small', 'tiny', 'short', 'thin', 'light'] },
    { word: 'run', definition: 'to move quickly on foot', distractors: ['walk', 'sit', 'sleep', 'eat', 'read'] },
    { word: 'cat', definition: 'a small furry pet that meows', distractors: ['dog', 'bird', 'fish', 'horse', 'cow'] },
    { word: 'help', definition: 'to give support to someone', distractors: ['hurt', 'hide', 'stop', 'leave', 'break'] },
    { word: 'water', definition: 'a clear liquid we drink', distractors: ['milk', 'gas', 'sand', 'rock', 'fire'] },
    { word: 'little', definition: 'small in size', distractors: ['huge', 'giant', 'tall', 'wide', 'heavy'] },
    { word: 'fast', definition: 'moving quickly', distractors: ['slow', 'still', 'late', 'soft', 'quiet'] },
    { word: 'slow', definition: 'moving without much speed', distractors: ['fast', 'quick', 'rapid', 'early', 'loud'] },
    { word: 'cold', definition: 'having a low temperature', distractors: ['hot', 'warm', 'dry', 'bright', 'soft'] },
    { word: 'warm', definition: 'a little hot, but not too hot', distractors: ['cold', 'frozen', 'wet', 'dark', 'hard'] },
    { word: 'look', definition: 'to use your eyes to see', distractors: ['listen', 'taste', 'touch', 'sleep', 'talk'] },
    { word: 'cry', definition: 'when tears come from your eyes', distractors: ['laugh', 'smile', 'dance', 'sleep', 'clap'] },
    { word: 'quiet', definition: 'making very little sound', distractors: ['loud', 'noisy', 'wild', 'bright', 'quick'] },
    { word: 'loud', definition: 'making a strong sound', distractors: ['quiet', 'silent', 'soft', 'tiny', 'slow'] },
    { word: 'soft', definition: 'not hard or rough to touch', distractors: ['hard', 'sharp', 'rough', 'heavy', 'loud'] },
    { word: 'hard', definition: 'firm and not easy to bend', distractors: ['soft', 'fluffy', 'gentle', 'wet', 'loose'] },
    { word: 'clean', definition: 'not dirty', distractors: ['muddy', 'messy', 'dusty', 'sticky', 'stained'] },
    { word: 'dirty', definition: 'covered with dirt or mess', distractors: ['clean', 'fresh', 'neat', 'washed', 'bright'] },
    { word: 'open', definition: 'not closed or shut', distractors: ['closed', 'locked', 'covered', 'hidden', 'sealed'] },
    { word: 'close', definition: 'to shut something', distractors: ['open', 'lift', 'start', 'throw', 'show'] },
    { word: 'start', definition: 'to begin doing something', distractors: ['finish', 'stop', 'end', 'rest', 'wait'] },
    { word: 'stop', definition: 'to no longer move or continue', distractors: ['start', 'go', 'begin', 'run', 'continue'] },
    { word: 'above', definition: 'higher than something else', distractors: ['below', 'under', 'inside', 'behind', 'over'] },
    { word: 'below', definition: 'lower than something else', distractors: ['above', 'over', 'outside', 'ahead', 'beside'] },
    { word: 'near', definition: 'not far away', distractors: ['far', 'distant', 'lost', 'high', 'deep'] },
    { word: 'far', definition: 'a long distance away', distractors: ['near', 'close', 'beside', 'inside', 'here'] },
    { word: 'empty', definition: 'having nothing inside', distractors: ['full', 'packed', 'filled', 'heavy', 'crowded'] },
    { word: 'full', definition: 'holding as much as it can', distractors: ['empty', 'bare', 'open', 'tiny', 'broken'] },
    { word: 'day', definition: 'the time when it is light outside', distractors: ['night', 'bed', 'dark', 'dusk', 'noon'] },
    { word: 'night', definition: 'the time when it is dark outside', distractors: ['morning', 'noon', 'day', 'sun', 'noon'] },
    { word: 'food', definition: 'something people or animals eat', distractors: ['clouds', 'air', 'sand', 'soap', 'music'] },
    { word: 'school', definition: 'a place where students go to learn', distractors: ['store', 'farm', 'park', 'hospital', 'garage'] },
    { word: 'teacher', definition: 'a person who helps students learn', distractors: ['doctor', 'pilot', 'farmer', 'chef', 'driver'] },
    { word: 'shape', definition: 'the form or outline of something', distractors: ['color', 'sound', 'taste', 'speed', 'temperature'] },
    { word: 'round', definition: 'shaped like a circle or ball', distractors: ['square', 'flat', 'pointed', 'straight', 'sharp'] },
    { word: 'square', definition: 'a shape with four equal sides', distractors: ['circle', 'triangle', 'oval', 'star', 'heart'] },
    { word: 'first', definition: 'coming before all the others', distractors: ['last', 'second', 'middle', 'later', 'final'] },
    { word: 'last', definition: 'coming after all the others', distractors: ['first', 'early', 'middle', 'next', 'beginning'] },
    { word: 'sad', definition: 'feeling unhappy', distractors: ['happy', 'glad', 'cheerful', 'excited', 'proud'] },
    { word: 'walk', definition: 'to move on foot', distractors: ['swim', 'nap', 'sit', 'sleep', 'crawl'] },
    { word: 'eat', definition: 'to swallow food', distractors: ['drink', 'sleep', 'read', 'listen', 'wash'] },
    { word: 'sit', definition: 'to put your body on a seat', distractors: ['stand', 'run', 'jump', 'walk', 'dance'] },
    { word: 'read', definition: 'to understand words', distractors: ['write', 'draw', 'sing', 'sleep', 'count'] },
    { word: 'write', definition: 'to make letters or words', distractors: ['read', 'erase', 'listen', 'sing', 'count'] },
    { word: 'hot', definition: 'having a high temperature', distractors: ['cold', 'cool', 'frozen', 'wet', 'dark'] },
    { word: 'wet', definition: 'covered with water', distractors: ['dry', 'dusty', 'clean', 'hard', 'warm'] },
    { word: 'dry', definition: 'not wet', distractors: ['wet', 'soaked', 'damp', 'muddy', 'sticky'] },
    { word: 'outside', definition: 'not inside something', distractors: ['inside', 'under', 'between', 'near', 'above'] },
    { word: 'before', definition: 'earlier than something else', distractors: ['after', 'later', 'last', 'next', 'final'] },
    { word: 'after', definition: 'later than something else', distractors: ['before', 'earlier', 'first', 'past', 'previous'] },
    { word: 'same', definition: 'exactly alike', distractors: ['different', 'unequal', 'opposite', 'separate', 'unlike'] },
    { word: 'home', definition: 'a place where someone lives', distractors: ['fence', 'store', 'jar', 'wall', 'road'] },
    { word: 'young', definition: 'not old', distractors: ['old', 'ancient', 'grown', 'late', 'large'] },
    { word: 'small', definition: 'little in size', distractors: ['big', 'huge', 'wide', 'heavy', 'tall'] },
    { word: 'jump', definition: 'to leap off the ground', distractors: ['sit', 'sleep', 'crawl', 'rest', 'hide'] },
    { word: 'friend', definition: 'a person you like and spend time with', distractors: ['stranger', 'enemy', 'crowd', 'shadow', 'rock'] },
    { word: 'smile', definition: 'to show happiness with your mouth', distractors: ['frown', 'cry', 'shout', 'hide', 'sleep'] },
    { word: 'dark', definition: 'having little or no light', distractors: ['bright', 'sunny', 'light', 'clear', 'shiny'] },
    { word: 'under', definition: 'beneath something', distractors: ['over', 'above', 'on', 'beside', 'inside'] },
    { word: 'grow', definition: 'to become bigger over time', distractors: ['shrink', 'stop', 'fade', 'break', 'fall'] },
    { word: 'kind', definition: 'friendly toward others', distractors: ['mean', 'rude', 'selfish', 'harsh', 'cruel'] },
    { word: 'new', definition: 'not used or seen before', distractors: ['old', 'worn', 'used', 'broken', 'ancient'] },
  ],

  2: [
    { word: 'brave', definition: 'willing to face danger without fear', distractors: ['scared', 'lazy', 'quiet', 'slow', 'weak'] },
    { word: 'whisper', definition: 'to speak very softly', distractors: ['shout', 'sing', 'laugh', 'yell', 'scream'] },
    { word: 'gentle', definition: 'soft and kind, not rough', distractors: ['harsh', 'loud', 'sharp', 'heavy', 'fast'] },
    { word: 'rescue', definition: 'to save someone from danger', distractors: ['ignore', 'trap', 'lose', 'hide', 'delay'] },
    { word: 'honest', definition: 'telling the truth', distractors: ['sneaky', 'rude', 'lazy', 'noisy', 'selfish'] },
    { word: 'gather', definition: 'to collect things together', distractors: ['scatter', 'drop', 'break', 'throw', 'split'] },
    { word: 'notice', definition: 'to become aware of something', distractors: ['forget', 'ignore', 'miss', 'hide', 'deny'] },
    { word: 'protect', definition: 'to keep something safe', distractors: ['harm', 'break', 'leave', 'expose', 'attack'] },
    { word: 'clever', definition: 'quick to solve problems', distractors: ['foolish', 'sleepy', 'slow', 'careless', 'confused'] },
    { word: 'curious', definition: 'wanting to know or learn more', distractors: ['bored', 'certain', 'angry', 'sleepy', 'careless'] },
    { word: 'discover', definition: 'to find something for the first time', distractors: ['lose', 'hide', 'forget', 'cover', 'ignore'] },
    { word: 'imagine', definition: 'to make a picture in your mind', distractors: ['measure', 'forget', 'erase', 'count', 'copy'] },
    { word: 'careful', definition: 'taking time to avoid mistakes', distractors: ['careless', 'reckless', 'rushed', 'wild', 'sloppy'] },
    { word: 'dangerous', definition: 'likely to cause harm or injury', distractors: ['safe', 'gentle', 'harmless', 'calm', 'helpful'] },
    { word: 'sturdy', definition: 'strong and not easily broken', distractors: ['fragile', 'weak', 'flimsy', 'soft', 'loose'] },
    { word: 'vanish', definition: 'to disappear suddenly', distractors: ['appear', 'arrive', 'remain', 'grow', 'shine'] },
    { word: 'arrive', definition: 'to reach a place', distractors: ['leave', 'depart', 'wander', 'return', 'hide'] },
    { word: 'depart', definition: 'to leave a place', distractors: ['arrive', 'enter', 'stay', 'remain', 'visit'] },
    { word: 'repair', definition: 'to fix something that is broken', distractors: ['damage', 'break', 'ruin', 'lose', 'hide'] },
    { word: 'search', definition: 'to look carefully for something', distractors: ['ignore', 'hide', 'lose', 'forget', 'avoid'] },
    { word: 'create', definition: 'to make something new', distractors: ['destroy', 'erase', 'break', 'copy', 'lose'] },
    { word: 'different', definition: 'not the same', distractors: ['same', 'equal', 'matching', 'identical', 'alike'] },
    { word: 'similar', definition: 'almost the same', distractors: ['different', 'opposite', 'unrelated', 'separate', 'unequal'] },
    { word: 'remember', definition: 'to bring something back to your mind', distractors: ['forget', 'ignore', 'erase', 'lose', 'miss'] },
    { word: 'explain', definition: 'to make an idea easier to understand', distractors: ['confuse', 'hide', 'deny', 'forget', 'mix'] },
    { word: 'delicious', definition: 'having a very good taste', distractors: ['bitter', 'awful', 'rotten', 'plain', 'sour'] },
    { word: 'enormous', definition: 'very large', distractors: ['tiny', 'little', 'small', 'narrow', 'short'] },
    { word: 'narrow', definition: 'not wide from side to side', distractors: ['wide', 'broad', 'huge', 'open', 'round'] },
    { word: 'wide', definition: 'having a lot of space from side to side', distractors: ['narrow', 'thin', 'tight', 'tiny', 'short'] },
    { word: 'crooked', definition: 'bent or not straight', distractors: ['straight', 'level', 'smooth', 'flat', 'even'] },
    { word: 'smooth', definition: 'even to the touch, without bumps', distractors: ['rough', 'bumpy', 'jagged', 'sharp', 'cracked'] },
    { word: 'rough', definition: 'not smooth; covered with bumps or uneven places', distractors: ['smooth', 'silky', 'even', 'flat', 'soft'] },
    { word: 'bright', definition: 'giving off a lot of light', distractors: ['dim', 'dark', 'dull', 'shadowy', 'faint'] },
    { word: 'dim', definition: 'not giving off much light', distractors: ['bright', 'shiny', 'glowing', 'sunny', 'clear'] },
    { word: 'lonely', definition: 'sad because you feel alone', distractors: ['cheerful', 'included', 'excited', 'proud', 'grateful'] },
    { word: 'proud', definition: 'pleased with something you did', distractors: ['ashamed', 'embarrassed', 'scared', 'worried', 'jealous'] },
    { word: 'nervous', definition: 'worried about what may happen', distractors: ['calm', 'relaxed', 'confident', 'sleepy', 'cheerful'] },
    { word: 'patient', definition: 'able to wait calmly', distractors: ['impatient', 'rushed', 'restless', 'angry', 'wild'] },
    { word: 'grateful', definition: 'feeling thankful', distractors: ['ungrateful', 'angry', 'jealous', 'bored', 'worried'] },
    { word: 'puzzled', definition: 'confused about something', distractors: ['certain', 'sure', 'confident', 'calm', 'prepared'] },
    { word: 'calm', definition: 'peaceful and not worried', distractors: ['nervous', 'angry', 'wild', 'frightened', 'restless'] },
    { word: 'cheerful', definition: 'happy and positive', distractors: ['sad', 'gloomy', 'angry', 'lonely', 'worried'] },
    { word: 'frightened', definition: 'feeling afraid', distractors: ['brave', 'calm', 'proud', 'excited', 'cheerful'] },
    { word: 'helpful', definition: 'ready to give help', distractors: ['harmful', 'selfish', 'rude', 'careless', 'lazy'] },
    { word: 'polite', definition: 'showing good manners', distractors: ['rude', 'mean', 'careless', 'wild', 'selfish'] },
    { word: 'sudden', definition: 'happening without warning', distractors: ['gradual', 'slow', 'expected', 'delayed', 'steady'] },
    { word: 'escape', definition: 'to get away from a place', distractors: ['enter', 'remain', 'return', 'approach', 'stay'] },
    { word: 'return', definition: 'to go back to a place', distractors: ['depart', 'leave', 'escape', 'vanish', 'wander'] },
    { word: 'invite', definition: 'to ask someone to join', distractors: ['exclude', 'refuse', 'avoid', 'hide', 'dismiss'] },
    { word: 'answer', definition: 'a response to a question', distractors: ['question', 'problem', 'guess', 'story', 'secret'] },
    { word: 'problem', definition: 'something that needs solving', distractors: ['solution', 'answer', 'reward', 'success', 'celebration'] },
    { word: 'message', definition: 'information sent to someone', distractors: ['silence', 'secret', 'object', 'place', 'shape'] },
    { word: 'silent', definition: 'making no sound', distractors: ['loud', 'noisy', 'talkative', 'bright', 'rough'] },
    { word: 'shallow', definition: 'not very deep', distractors: ['deep', 'wide', 'high', 'long', 'steep'] },
    { word: 'deep', definition: 'going far down', distractors: ['shallow', 'flat', 'narrow', 'short', 'light'] },
    { word: 'crowded', definition: 'filled with many people', distractors: ['empty', 'quiet', 'lonely', 'wide', 'clear'] },
    { word: 'generous', definition: 'happy to share with others', distractors: ['selfish', 'greedy', 'stingy', 'mean', 'rude'] },
    { word: 'obey', definition: 'to do what you are told', distractors: ['disobey', 'refuse', 'ignore', 'rebel', 'resist'] },
    { word: 'wander', definition: 'to walk without a set plan', distractors: ['stay', 'rush', 'remain', 'settle', 'focus'] },
    { word: 'sparkle', definition: 'small bright flashes', distractors: ['fade', 'dim', 'dull', 'darken', 'hide'] },
  ],

  3: [
    { word: 'ancient', definition: 'very old, from long ago', distractors: ['modern', 'new', 'recent', 'fresh', 'young'] },
    { word: 'journey', definition: 'a trip from one place to another', distractors: ['rest', 'home', 'pause', 'stop', 'delay'] },
    { word: 'courage', definition: 'the strength to do something scary', distractors: ['fear', 'doubt', 'weakness', 'shame', 'panic'] },
    { word: 'decision', definition: 'a choice you make after thinking', distractors: ['accident', 'guess', 'mistake', 'delay', 'confusion'] },
    { word: 'describe', definition: 'to explain what something is like', distractors: ['hide', 'ignore', 'forget', 'destroy', 'misplace'] },
    { word: 'energy', definition: 'power that lets things move', distractors: ['silence', 'darkness', 'stillness', 'emptiness', 'weakness'] },
    { word: 'fragile', definition: 'easy to break or damage', distractors: ['strong', 'tough', 'solid', 'heavy', 'thick'] },
    { word: 'precious', definition: 'very valuable or special', distractors: ['cheap', 'useless', 'common', 'broken', 'empty'] },
    { word: 'adapt', definition: 'to change to fit new conditions', distractors: ['remain', 'refuse', 'freeze', 'repeat', 'ignore'] },
    { word: 'approach', definition: 'to move closer to something', distractors: ['retreat', 'leave', 'avoid', 'escape', 'depart'] },
    { word: 'astonished', definition: 'very surprised', distractors: ['bored', 'calm', 'uninterested', 'prepared', 'sleepy'] },
    { word: 'attempt', definition: 'to try to do something', distractors: ['refuse', 'quit', 'avoid', 'ignore', 'finish'] },
    { word: 'avoid', definition: 'to stay away from something', distractors: ['approach', 'enter', 'seek', 'follow', 'join'] },
    { word: 'calculate', definition: 'to find an answer using numbers', distractors: ['guess', 'erase', 'draw', 'describe', 'imagine'] },
    { word: 'consequence', definition: 'what happens because of an action', distractors: ['cause', 'plan', 'question', 'choice', 'beginning'] },
    { word: 'contain', definition: 'to hold something inside', distractors: ['release', 'spill', 'scatter', 'empty', 'remove'] },
    { word: 'determine', definition: 'to find out or decide something', distractors: ['ignore', 'wonder', 'forget', 'confuse', 'delay'] },
    { word: 'eager', definition: 'very excited to do something', distractors: ['reluctant', 'bored', 'unwilling', 'sleepy', 'hesitant'] },
    { word: 'effect', definition: 'a change caused by something else', distractors: ['cause', 'reason', 'plan', 'question', 'source'] },
    { word: 'examine', definition: 'to look at something carefully', distractors: ['ignore', 'glance', 'hide', 'forget', 'avoid'] },
    { word: 'familiar', definition: 'something you know well', distractors: ['strange', 'unknown', 'new', 'mysterious', 'foreign'] },
    { word: 'fortunate', definition: 'having good luck', distractors: ['unlucky', 'unfortunate', 'miserable', 'careless', 'ordinary'] },
    { word: 'gradual', definition: 'happening slowly over time', distractors: ['sudden', 'instant', 'immediate', 'rapid', 'abrupt'] },
    { word: 'identify', definition: 'to recognize what something is', distractors: ['confuse', 'hide', 'forget', 'misplace', 'ignore'] },
    { word: 'increase', definition: 'to become greater', distractors: ['decrease', 'shrink', 'reduce', 'lessen', 'drop'] },
    { word: 'locate', definition: 'to find where something is', distractors: ['lose', 'hide', 'misplace', 'forget', 'remove'] },
    { word: 'ordinary', definition: 'normal or not unusual', distractors: ['rare', 'strange', 'special', 'unusual', 'remarkable'] },
    { word: 'persuade', definition: 'to convince someone', distractors: ['discourage', 'confuse', 'force', 'ignore', 'refuse'] },
    { word: 'prevent', definition: 'to stop something from happening', distractors: ['allow', 'cause', 'encourage', 'begin', 'permit'] },
    { word: 'rare', definition: 'not common', distractors: ['common', 'usual', 'frequent', 'ordinary', 'plentiful'] },
    { word: 'region', definition: 'a large area of land', distractors: ['object', 'person', 'moment', 'sound', 'number'] },
    { word: 'solution', definition: 'an answer to a problem', distractors: ['problem', 'question', 'mistake', 'obstacle', 'confusion'] },
    { word: 'suitable', definition: 'appropriate for a purpose', distractors: ['wrong', 'useless', 'harmful', 'awkward', 'impossible'] },
    { word: 'survive', definition: 'to stay alive', distractors: ['fail', 'vanish', 'surrender', 'collapse', 'perish'] },
    { word: 'threaten', definition: 'to show that harm may happen', distractors: ['protect', 'comfort', 'help', 'rescue', 'welcome'] },
    { word: 'absorb', definition: 'to take in liquid', distractors: ['release', 'spill', 'pour', 'scatter', 'remove'] },
    { word: 'assist', definition: 'to help someone', distractors: ['hinder', 'ignore', 'harm', 'stop', 'refuse'] },
    { word: 'capture', definition: 'to catch and hold something', distractors: ['release', 'free', 'lose', 'avoid', 'miss'] },
    { word: 'connect', definition: 'to join two things together', distractors: ['separate', 'disconnect', 'divide', 'scatter', 'remove'] },
    { word: 'confident', definition: 'sure of yourself', distractors: ['nervous', 'uncertain', 'afraid', 'doubtful', 'confused'] },
    { word: 'damage', definition: 'to harm or break something', distractors: ['repair', 'protect', 'improve', 'fix', 'preserve'] },
    { word: 'distant', definition: 'far away', distractors: ['nearby', 'close', 'local', 'beside', 'adjacent'] },
    { word: 'entire', definition: 'including every part', distractors: ['partial', 'half', 'some', 'limited', 'incomplete'] },
    { word: 'measure', definition: 'to find the size of something', distractors: ['guess', 'ignore', 'erase', 'hide', 'mix'] },
    { word: 'prefer', definition: 'to like one choice more', distractors: ['dislike', 'reject', 'avoid', 'ignore', 'forget'] },
    { word: 'purpose', definition: 'the reason something is done', distractors: ['accident', 'mistake', 'result', 'question', 'detail'] },
    { word: 'reduce', definition: 'to make something smaller', distractors: ['increase', 'expand', 'raise', 'grow', 'multiply'] },
    { word: 'separate', definition: 'to move things apart', distractors: ['combine', 'join', 'connect', 'gather', 'mix'] },
    { word: 'visible', definition: 'able to be seen', distractors: ['hidden', 'invisible', 'covered', 'secret', 'dark'] },
    { word: 'habitat', definition: 'the place where something lives', distractors: ['predator', 'season', 'weather', 'fossil', 'tool'] },
    { word: 'migrate', definition: 'to move to another place', distractors: ['remain', 'stay', 'settle', 'hide', 'shrink'] },
    { word: 'opinion', definition: 'what a person believes', distractors: ['fact', 'proof', 'law', 'measurement', 'rule'] },
  ],

  4: [
    { word: 'analyze', definition: 'to study something carefully', distractors: ['ignore', 'guess', 'forget', 'destroy', 'hide'] },
    { word: 'contrast', definition: 'to show how things are different', distractors: ['match', 'copy', 'blend', 'repeat', 'combine'] },
    { word: 'evidence', definition: 'facts that support an idea', distractors: ['opinion', 'rumor', 'guess', 'myth', 'joke'] },
    { word: 'frequent', definition: 'happening often', distractors: ['rare', 'never', 'once', 'seldom', 'occasional'] },
    { word: 'influence', definition: 'the power to change someone', distractors: ['ignore', 'weaken', 'block', 'remove', 'silence'] },
    { word: 'observe', definition: 'to watch carefully', distractors: ['ignore', 'forget', 'miss', 'disturb', 'interrupt'] },
    { word: 'predict', definition: 'to say what you think will happen', distractors: ['forget', 'deny', 'ignore', 'confuse', 'delay'] },
    { word: 'require', definition: 'to need something', distractors: ['reject', 'avoid', 'refuse', 'skip', 'ignore'] },
    { word: 'summary', definition: 'a short statement of the main idea', distractors: ['detail', 'story', 'joke', 'secret', 'error'] },
    { word: 'tradition', definition: 'a custom passed down over time', distractors: ['invention', 'accident', 'surprise', 'mistake', 'novelty'] },
    { word: 'accurate', definition: 'correct and free from mistakes', distractors: ['wrong', 'false', 'careless', 'rough', 'uncertain'] },
    { word: 'achieve', definition: 'to successfully reach a goal', distractors: ['fail', 'abandon', 'lose', 'avoid', 'delay'] },
    { word: 'approximate', definition: 'close, but not exact', distractors: ['exact', 'perfect', 'certain', 'identical', 'complete'] },
    { word: 'classify', definition: 'to sort things into groups', distractors: ['scatter', 'mix', 'ignore', 'destroy', 'separate randomly'] },
    { word: 'complex', definition: 'not simple', distractors: ['simple', 'easy', 'plain', 'basic', 'obvious'] },
    { word: 'consume', definition: 'to use up, eat, or drink something', distractors: ['save', 'store', 'produce', 'protect', 'collect'] },
    { word: 'demonstrate', definition: 'to show how something works', distractors: ['hide', 'confuse', 'deny', 'forget', 'prevent'] },
    { word: 'distribute', definition: 'to give or spread things out', distractors: ['collect', 'gather', 'hoard', 'hide', 'keep'] },
    { word: 'encounter', definition: 'to meet unexpectedly', distractors: ['avoid', 'escape', 'ignore', 'miss', 'leave'] },
    { word: 'estimate', definition: 'a careful guess about an amount', distractors: ['exact', 'proof', 'measurement', 'fact', 'certainty'] },
    { word: 'evaluate', definition: 'to judge the quality of something', distractors: ['ignore', 'copy', 'hide', 'guess', 'repeat'] },
    { word: 'extract', definition: 'to pull something out', distractors: ['insert', 'add', 'attach', 'combine', 'store'] },
    { word: 'flexible', definition: 'able to bend easily', distractors: ['rigid', 'stiff', 'fixed', 'brittle', 'solid'] },
    { word: 'indicate', definition: 'to point out or show something', distractors: ['hide', 'deny', 'erase', 'confuse', 'ignore'] },
    { word: 'investigate', definition: 'to examine something', distractors: ['ignore', 'assume', 'guess', 'forget', 'avoid'] },
    { word: 'modify', definition: 'to change something slightly', distractors: ['preserve', 'freeze', 'copy', 'ignore', 'destroy'] },
    { word: 'organize', definition: 'to arrange things', distractors: ['scatter', 'mix', 'confuse', 'ruin', 'misplace'] },
    { word: 'participate', definition: 'to take part in an activity', distractors: ['watch', 'avoid', 'quit', 'ignore', 'leave'] },
    { word: 'preserve', definition: 'to protect something', distractors: ['destroy', 'damage', 'waste', 'abandon', 'erase'] },
    { word: 'process', definition: 'a series of steps', distractors: ['accident', 'shortcut', 'object', 'place', 'opinion'] },
    { word: 'recommend', definition: 'to suggest something', distractors: ['forbid', 'reject', 'hide', 'ignore', 'criticize'] },
    { word: 'represent', definition: 'to stand for something else', distractors: ['erase', 'hide', 'destroy', 'separate', 'deny'] },
    { word: 'specific', definition: 'clearly named or exact', distractors: ['general', 'vague', 'broad', 'unclear', 'random'] },
    { word: 'temporary', definition: 'lasting only for a limited time', distractors: ['permanent', 'lasting', 'endless', 'fixed', 'eternal'] },
    { word: 'accomplish', definition: 'to successfully finish something', distractors: ['fail', 'quit', 'delay', 'avoid', 'abandon'] },
    { word: 'alter', definition: 'to change something', distractors: ['preserve', 'keep', 'repeat', 'freeze', 'restore'] },
    { word: 'confirm', definition: 'to show that something is true', distractors: ['deny', 'doubt', 'hide', 'refute', 'question'] },
    { word: 'construct', definition: 'to build something', distractors: ['destroy', 'damage', 'remove', 'break', 'erase'] },
    { word: 'decrease', definition: 'to become smaller or less', distractors: ['increase', 'grow', 'rise', 'expand', 'multiply'] },
    { word: 'efficient', definition: 'not wasting time or effort', distractors: ['wasteful', 'slow', 'careless', 'confusing', 'ineffective'] },
    { word: 'expand', definition: 'to become larger', distractors: ['shrink', 'reduce', 'decrease', 'narrow', 'contract'] },
    { word: 'initial', definition: 'coming at the beginning', distractors: ['final', 'last', 'later', 'ending', 'previous'] },
    { word: 'obstacle', definition: 'something that blocks progress', distractors: ['aid', 'solution', 'shortcut', 'reward', 'advantage'] },
    { word: 'permit', definition: 'to allow something', distractors: ['forbid', 'prevent', 'block', 'refuse', 'stop'] },
    { word: 'respond', definition: 'to answer or react', distractors: ['ignore', 'avoid', 'hide', 'delay', 'forget'] },
    { word: 'select', definition: 'to choose something', distractors: ['reject', 'ignore', 'lose', 'hide', 'remove'] },
    { word: 'vary', definition: 'to change or be different', distractors: ['remain', 'match', 'repeat', 'stay', 'equal'] },
    { word: 'verify', definition: 'to check if something is correct', distractors: ['guess', 'assume', 'ignore', 'hide', 'invent'] },
    { word: 'resource', definition: 'something useful that can help', distractors: ['obstacle', 'waste', 'problem', 'burden', 'risk'] },
  ],

  5: [
    { word: 'abundant', definition: 'more than enough; plentiful', distractors: ['scarce', 'rare', 'empty', 'limited', 'tiny'] },
    { word: 'benefit', definition: 'something good that helps you', distractors: ['harm', 'loss', 'problem', 'cost', 'risk'] },
    { word: 'consider', definition: 'to think about carefully', distractors: ['ignore', 'reject', 'forget', 'rush', 'dismiss'] },
    { word: 'decline', definition: 'to become smaller or weaker', distractors: ['grow', 'rise', 'increase', 'expand', 'surge'] },
    { word: 'essential', definition: 'absolutely necessary', distractors: ['optional', 'extra', 'useless', 'minor', 'trivial'] },
    { word: 'factor', definition: 'something that affects a result', distractors: ['accident', 'coincidence', 'mistake', 'joke', 'guess'] },
    { word: 'maintain', definition: 'to keep something in good condition', distractors: ['break', 'neglect', 'abandon', 'destroy', 'ruin'] },
    { word: 'occur', definition: 'to happen', distractors: ['vanish', 'stop', 'fail', 'pause', 'disappear'] },
    { word: 'significant', definition: 'important or meaningful', distractors: ['minor', 'trivial', 'small', 'useless', 'random'] },
    { word: 'acknowledge', definition: 'to admit you are aware of something', distractors: ['deny', 'ignore', 'hide', 'forget', 'reject'] },
    { word: 'alternative', definition: 'another choice or possibility', distractors: ['requirement', 'result', 'rule', 'fact', 'problem'] },
    { word: 'anticipate', definition: 'to expect something before it happens', distractors: ['forget', 'doubt', 'ignore', 'remember afterward', 'prevent'] },
    { word: 'apparent', definition: 'seeming to be true', distractors: ['hidden', 'unclear', 'secret', 'impossible', 'invisible'] },
    { word: 'contradict', definition: 'to say the opposite', distractors: ['agree', 'confirm', 'support', 'repeat', 'accept'] },
    { word: 'critical', definition: 'very important to an outcome', distractors: ['minor', 'optional', 'trivial', 'unrelated', 'ordinary'] },
    { word: 'diminish', definition: 'to become smaller or lesser', distractors: ['increase', 'expand', 'strengthen', 'multiply', 'enlarge'] },
    { word: 'elaborate', definition: 'to explain more fully', distractors: ['shorten', 'hide', 'simplify', 'erase', 'ignore'] },
    { word: 'emerge', definition: 'to come out or appear', distractors: ['vanish', 'hide', 'sink', 'disappear', 'retreat'] },
    { word: 'emphasize', definition: 'to give special importance', distractors: ['ignore', 'minimize', 'hide', 'weaken', 'dismiss'] },
    { word: 'generate', definition: 'to produce or create something', distractors: ['destroy', 'remove', 'consume', 'lose', 'prevent'] },
    { word: 'illustrate', definition: 'to show something with pictures', distractors: ['confuse', 'hide', 'deny', 'erase', 'complicate'] },
    { word: 'impact', definition: 'a strong effect or influence', distractors: ['cause', 'detail', 'guess', 'silence', 'absence'] },
    { word: 'justify', definition: 'to give reasons or evidence', distractors: ['deny', 'guess', 'hide', 'contradict', 'ignore'] },
    { word: 'principle', definition: 'a basic rule that guides actions', distractors: ['accident', 'rumor', 'exception', 'object', 'mistake'] },
    { word: 'resist', definition: 'to oppose something', distractors: ['accept', 'surrender', 'allow', 'welcome', 'obey'] },
    { word: 'transform', definition: 'to change greatly in form', distractors: ['preserve', 'maintain', 'freeze', 'repeat', 'restore'] },
    { word: 'widespread', definition: 'happening over a large area', distractors: ['rare', 'local', 'limited', 'isolated', 'narrow'] },
    { word: 'reluctant', definition: 'not eager to do something', distractors: ['eager', 'willing', 'excited', 'ready', 'enthusiastic'] },
    { word: 'assume', definition: 'to accept something as true without proof', distractors: ['verify', 'prove', 'confirm', 'measure', 'test'] },
    { word: 'capacity', definition: 'the amount something can hold', distractors: ['surface', 'shape', 'color', 'weight', 'edge'] },
    { word: 'concentrate', definition: 'to give full attention', distractors: ['distract', 'ignore', 'wander', 'forget', 'relax'] },
    { word: 'consistent', definition: 'staying the same in quality', distractors: ['random', 'uneven', 'changing', 'unreliable', 'irregular'] },
    { word: 'context', definition: 'the situation around something', distractors: ['isolation', 'answer', 'object', 'number', 'title'] },
    { word: 'convert', definition: 'to change into another form', distractors: ['preserve', 'maintain', 'restore', 'freeze', 'repeat'] },
    { word: 'disrupt', definition: 'to interrupt normal activity', distractors: ['continue', 'support', 'organize', 'stabilize', 'assist'] },
    { word: 'exclude', definition: 'to leave something out', distractors: ['include', 'invite', 'accept', 'add', 'welcome'] },
    { word: 'infer', definition: 'to reach an idea from clues', distractors: ['guess blindly', 'ignore', 'copy', 'forget', 'deny'] },
    { word: 'potential', definition: 'the ability to succeed', distractors: ['failure', 'limit', 'weakness', 'damage', 'loss'] },
    { word: 'restrict', definition: 'to limit what is allowed', distractors: ['allow', 'expand', 'free', 'encourage', 'permit'] },
    { word: 'retain', definition: 'to keep something', distractors: ['discard', 'lose', 'release', 'remove', 'abandon'] },
    { word: 'sufficient', definition: 'enough for what is needed', distractors: ['insufficient', 'lacking', 'scarce', 'limited', 'empty'] },
    { word: 'valid', definition: 'supported by good evidence', distractors: ['false', 'invalid', 'weak', 'random', 'unsupported'] },
    { word: 'revise', definition: 'to modify a plan', distractors: ['keep', 'erase', 'ignore', 'copy', 'abandon'] },
    { word: 'theme', definition: 'the main message of a story', distractors: ['detail', 'title', 'character', 'setting', 'author'] },
  ],

  6: [
    { word: 'accumulate', definition: 'to collect over time', distractors: ['scatter', 'lose', 'waste', 'drain', 'reduce'] },
    { word: 'conclude', definition: 'to decide after thinking', distractors: ['begin', 'guess', 'wonder', 'delay', 'confuse'] },
    { word: 'distinct', definition: 'clearly different or separate', distractors: ['similar', 'identical', 'mixed', 'vague', 'blended'] },
    { word: 'establish', definition: 'to set up something that lasts', distractors: ['destroy', 'remove', 'cancel', 'abandon', 'break'] },
    { word: 'interpret', definition: 'to explain the meaning of something', distractors: ['ignore', 'misread', 'confuse', 'hide', 'forget'] },
    { word: 'method', definition: 'a way of doing something', distractors: ['accident', 'chaos', 'guess', 'luck', 'surprise'] },
    { word: 'relevant', definition: 'connected to what is being discussed', distractors: ['random', 'unrelated', 'useless', 'confusing', 'distant'] },
    { word: 'structure', definition: 'the way parts are arranged', distractors: ['chaos', 'mess', 'ruin', 'gap', 'void'] },
    { word: 'transfer', definition: 'to move from one place to another', distractors: ['keep', 'hold', 'store', 'block', 'trap'] },
    { word: 'articulate', definition: 'to express an idea clearly', distractors: ['mumble', 'confuse', 'conceal', 'misstate', 'silence'] },
    { word: 'compile', definition: 'to collect information into one place', distractors: ['scatter', 'discard', 'separate', 'erase', 'destroy'] },
    { word: 'comprehensive', definition: 'including all important parts', distractors: ['partial', 'limited', 'incomplete', 'narrow', 'brief'] },
    { word: 'conventional', definition: 'following what is commonly done', distractors: ['unusual', 'experimental', 'original', 'rebellious', 'unexpected'] },
    { word: 'criteria', definition: 'standards used to judge something', distractors: ['results', 'opinions', 'accidents', 'examples', 'questions'] },
    { word: 'deduce', definition: 'to reach a conclusion from facts', distractors: ['guess', 'assume', 'forget', 'ignore', 'invent'] },
    { word: 'differentiate', definition: 'to show differences', distractors: ['combine', 'confuse', 'match', 'merge', 'equalize'] },
    { word: 'facilitate', definition: 'to make a process easier', distractors: ['hinder', 'block', 'delay', 'complicate', 'prevent'] },
    { word: 'formulate', definition: 'to develop a plan carefully', distractors: ['abandon', 'erase', 'ignore', 'destroy', 'improvise blindly'] },
    { word: 'isolate', definition: 'to separate something', distractors: ['combine', 'connect', 'merge', 'gather', 'include'] },
    { word: 'objective', definition: 'based on facts', distractors: ['biased', 'emotional', 'personal', 'subjective', 'prejudiced'] },
    { word: 'reinforce', definition: 'to strengthen something', distractors: ['weaken', 'undermine', 'damage', 'remove', 'oppose'] },
    { word: 'subsequent', definition: 'coming after something else', distractors: ['prior', 'earlier', 'previous', 'initial', 'first'] },
    { word: 'transition', definition: 'a change from one state to another', distractors: ['stability', 'pause', 'repetition', 'ending', 'barrier'] },
    { word: 'allocate', definition: 'to set aside something for a purpose', distractors: ['waste', 'scatter', 'remove', 'ignore', 'lose'] },
    { word: 'coincide', definition: 'to happen at the same time', distractors: ['differ', 'separate', 'precede', 'follow', 'conflict'] },
    { word: 'contemporary', definition: 'belonging to the present time', distractors: ['ancient', 'historic', 'outdated', 'old-fashioned', 'past'] },
    { word: 'dominate', definition: 'to have the most control', distractors: ['submit', 'follow', 'yield', 'weaken', 'withdraw'] },
    { word: 'fundamental', definition: 'basic and very important', distractors: ['minor', 'optional', 'extra', 'advanced', 'trivial'] },
    { word: 'inhibit', definition: 'to slow something down', distractors: ['encourage', 'allow', 'support', 'increase', 'enable'] },
    { word: 'mediate', definition: 'to help settle a disagreement', distractors: ['provoke', 'worsen', 'ignore', 'divide', 'oppose'] },
    { word: 'precede', definition: 'to come before something', distractors: ['follow', 'succeed', 'end', 'finish', 'conclude'] },
    { word: 'prohibit', definition: 'to forbid something', distractors: ['allow', 'permit', 'approve', 'encourage', 'accept'] },
    { word: 'undertake', definition: 'to begin a task', distractors: ['avoid', 'refuse', 'abandon', 'ignore', 'delay'] },
    { word: 'acquire', definition: 'to obtain something', distractors: ['lose', 'abandon', 'discard', 'refuse', 'release'] },
    { word: 'adjacent', definition: 'beside something', distractors: ['distant', 'remote', 'separate', 'opposite', 'isolated'] },
    { word: 'adjust', definition: 'to change something slightly', distractors: ['freeze', 'ignore', 'preserve', 'repeat', 'break'] },
    { word: 'aspect', definition: 'one feature of something', distractors: ['whole', 'total', 'sum', 'absence', 'chaos'] },
    { word: 'convey', definition: 'to communicate an idea', distractors: ['hide', 'conceal', 'confuse', 'withhold', 'silence'] },
    { word: 'correspond', definition: 'to be similar to something', distractors: ['differ', 'conflict', 'oppose', 'contradict', 'clash'] },
  ],

  7: [
    { word: 'ambiguous', definition: 'having more than one meaning', distractors: ['clear', 'obvious', 'exact', 'certain', 'precise'] },
    { word: 'compensate', definition: 'to make up for a mistake', distractors: ['ignore', 'worsen', 'neglect', 'refuse', 'avoid'] },
    { word: 'contribute', definition: 'to give something', distractors: ['withhold', 'steal', 'block', 'remove', 'hinder'] },
    { word: 'derive', definition: 'to get something from a source', distractors: ['lose', 'destroy', 'reject', 'ignore', 'waste'] },
    { word: 'equivalent', definition: 'equal in amount', distractors: ['different', 'opposite', 'lesser', 'unrelated', 'weaker'] },
    { word: 'hypothesis', definition: 'a testable idea', distractors: ['proof', 'fact', 'law', 'guess', 'joke'] },
    { word: 'imply', definition: 'to suggest something', distractors: ['deny', 'state', 'prove', 'ignore', 'confess'] },
    { word: 'perspective', definition: 'a point of view', distractors: ['fact', 'object', 'rule', 'tool', 'number'] },
    { word: 'proportion', definition: 'a part compared to the whole', distractors: ['whole', 'total', 'sum', 'limit', 'edge'] },
    { word: 'sequence', definition: 'an ordered list of steps', distractors: ['random', 'chaos', 'mix', 'pause', 'gap'] },
    { word: 'ascertain', definition: 'to find out something', distractors: ['guess', 'wonder', 'assume', 'ignore', 'misunderstand'] },
    { word: 'compatible', definition: 'able to exist together', distractors: ['incompatible', 'conflicting', 'opposed', 'unrelated', 'mismatched'] },
    { word: 'constrain', definition: 'to restrict what can happen', distractors: ['free', 'expand', 'encourage', 'release', 'enable'] },
    { word: 'inevitable', definition: 'certain to happen', distractors: ['avoidable', 'unlikely', 'optional', 'uncertain', 'preventable'] },
    { word: 'intrinsic', definition: 'belonging naturally to something', distractors: ['external', 'added', 'temporary', 'borrowed', 'accidental'] },
    { word: 'manipulate', definition: 'to control something skillfully', distractors: ['ignore', 'release', 'observe', 'abandon', 'accept'] },
    { word: 'prevalent', definition: 'common or widespread', distractors: ['rare', 'scarce', 'unusual', 'isolated', 'absent'] },
    { word: 'rational', definition: 'based on reason and logic', distractors: ['irrational', 'emotional', 'random', 'reckless', 'illogical'] },
    { word: 'scrutinize', definition: 'to examine something closely', distractors: ['glance', 'ignore', 'overlook', 'skim', 'dismiss'] },
    { word: 'analogous', definition: 'similar in important ways', distractors: ['unrelated', 'opposite', 'different', 'random', 'incompatible'] },
    { word: 'concurrent', definition: 'happening at the same time', distractors: ['separate', 'earlier', 'later', 'sequential', 'delayed'] },
    { word: 'detrimental', definition: 'causing harm', distractors: ['beneficial', 'helpful', 'harmless', 'protective', 'useful'] },
    { word: 'empirical', definition: 'based on evidence', distractors: ['imaginary', 'unsupported', 'theoretical', 'random', 'unverified'] },
    { word: 'extrapolate', definition: 'to predict using information', distractors: ['ignore', 'measure', 'record', 'repeat', 'summarize'] },
    { word: 'feasible', definition: 'possible and practical', distractors: ['impossible', 'unrealistic', 'unworkable', 'unlikely', 'harmful'] },
    { word: 'predominant', definition: 'most common', distractors: ['minor', 'rare', 'weak', 'secondary', 'unusual'] },
    { word: 'synthesize', definition: 'to combine ideas', distractors: ['separate', 'copy', 'discard', 'isolate', 'repeat'] },
    { word: 'tentative', definition: 'not final or certain', distractors: ['final', 'definite', 'confirmed', 'permanent', 'settled'] },
    { word: 'validate', definition: 'to show that something is correct', distractors: ['refute', 'reject', 'weaken', 'ignore', 'contradict'] },
    { word: 'attribute', definition: 'a feature of something', distractors: ['accident', 'absence', 'error', 'mystery', 'obstacle'] },
    { word: 'comprise', definition: 'to be made up of certain parts', distractors: ['exclude', 'omit', 'lack', 'divide', 'scatter'] },
    { word: 'conceive', definition: 'to form an idea in the mind', distractors: ['forget', 'reject', 'ignore', 'erase', 'dismiss'] },
    { word: 'conform', definition: 'to follow a rule', distractors: ['rebel', 'resist', 'deviate', 'oppose', 'defy'] },
    { word: 'constitute', definition: 'to make up or form something', distractors: ['destroy', 'remove', 'dismantle', 'exclude', 'ruin'] },
    { word: 'controversy', definition: 'a serious public disagreement', distractors: ['agreement', 'harmony', 'consensus', 'peace', 'unity'] },
  ],

  8: [
    { word: 'advocate', definition: 'to support a cause', distractors: ['oppose', 'reject', 'ignore', 'attack', 'abandon'] },
    { word: 'bias', definition: 'an unfair view against something', distractors: ['fairness', 'balance', 'truth', 'proof', 'neutrality'] },
    { word: 'coherent', definition: 'logical and easy to follow', distractors: ['confusing', 'random', 'broken', 'vague', 'messy'] },
    { word: 'diverse', definition: 'showing a great deal of variety', distractors: ['uniform', 'identical', 'narrow', 'limited', 'same'] },
    { word: 'explicit', definition: 'stated clearly and directly', distractors: ['hidden', 'vague', 'implied', 'secret', 'unclear'] },
    { word: 'integrate', definition: 'to combine parts into a whole', distractors: ['separate', 'split', 'remove', 'isolate', 'break'] },
    { word: 'paraphrase', definition: 'to restate something in new words', distractors: ['quote', 'copy', 'ignore', 'delete', 'misquote'] },
    { word: 'preliminary', definition: 'coming before the main event', distractors: ['final', 'last', 'complete', 'main', 'ultimate'] },
    { word: 'refute', definition: 'to prove a statement is wrong', distractors: ['support', 'confirm', 'accept', 'praise', 'ignore'] },
    { word: 'sustain', definition: 'to keep something going', distractors: ['stop', 'end', 'break', 'abandon', 'weaken'] },
    { word: 'anomaly', definition: 'something different from the norm', distractors: ['pattern', 'standard', 'rule', 'average', 'routine'] },
    { word: 'contentious', definition: 'likely to cause disagreement', distractors: ['peaceful', 'uncontroversial', 'agreeable', 'settled', 'harmony'] },
    { word: 'discrepancy', definition: 'a difference between things', distractors: ['agreement', 'match', 'consistency', 'similarity', 'balance'] },
    { word: 'exacerbate', definition: 'to make a problem worse', distractors: ['improve', 'relieve', 'reduce', 'solve', 'ease'] },
    { word: 'ubiquitous', definition: 'appearing almost everywhere', distractors: ['rare', 'scarce', 'hidden', 'local', 'isolated'] },
    { word: 'circumvent', definition: 'to find a way around an obstacle', distractors: ['confront', 'follow', 'obey', 'accept', 'enter'] },
    { word: 'delineate', definition: 'to describe something clearly', distractors: ['obscure', 'confuse', 'hide', 'blur', 'ignore'] },
    { word: 'disseminate', definition: 'to spread information widely', distractors: ['conceal', 'withhold', 'hide', 'collect', 'limit'] },
    { word: 'incongruous', definition: 'not matching its surroundings', distractors: ['fitting', 'consistent', 'matching', 'suitable', 'harmonious'] },
    { word: 'inherent', definition: 'existing as natural', distractors: ['external', 'added', 'temporary', 'optional', 'borrowed'] },
    { word: 'pervasive', definition: 'spread throughout an area', distractors: ['isolated', 'rare', 'limited', 'local', 'absent'] },
    { word: 'assertion', definition: 'a confident statement', distractors: ['question', 'silence', 'doubt', 'guess', 'rumor'] },
    { word: 'authentic', definition: 'genuine and not a copy or fake', distractors: ['false', 'fake', 'counterfeit', 'imitation', 'artificial'] },
    { word: 'compelling', definition: 'strong enough to convince', distractors: ['weak', 'dull', 'unconvincing', 'boring', 'forgettable'] },
    { word: 'credible', definition: 'believable and worthy of trust', distractors: ['unbelievable', 'false', 'doubtful', 'unreliable', 'absurd'] },
    { word: 'critique', definition: 'a careful judgment', distractors: ['summary', 'copy', 'guess', 'silence', 'rumor'] },
    { word: 'cultivate', definition: 'to encourage growth', distractors: ['neglect', 'destroy', 'abandon', 'suppress', 'ignore'] },
    { word: 'deficient', definition: 'lacking what is needed', distractors: ['complete', 'sufficient', 'abundant', 'adequate', 'full'] },
    { word: 'depict', definition: 'to show in words or pictures', distractors: ['hide', 'conceal', 'erase', 'distort', 'ignore'] },
    { word: 'deteriorate', definition: 'to become worse over time', distractors: ['improve', 'recover', 'strengthen', 'flourish', 'restore'] },
  ],

  9: [
    { word: 'arbitrary', definition: 'based on random choice', distractors: ['logical', 'planned', 'fair', 'reasoned', 'systematic'] },
    { word: 'connotation', definition: 'a feeling suggested by a word', distractors: ['definition', 'spelling', 'sound', 'grammar', 'syllable'] },
    { word: 'corroborate', definition: 'to confirm with evidence', distractors: ['deny', 'refute', 'weaken', 'contradict', 'ignore'] },
    { word: 'diligent', definition: 'careful in work or effort', distractors: ['lazy', 'careless', 'hasty', 'sloppy', 'idle'] },
    { word: 'eloquent', definition: 'fluent in speaking', distractors: ['silent', 'awkward', 'confused', 'rude', 'mumbled'] },
    { word: 'mitigate', definition: 'to make something less severe', distractors: ['worsen', 'increase', 'cause', 'ignore', 'provoke'] },
    { word: 'nuance', definition: 'a subtle difference in meaning', distractors: ['obvious', 'clarity', 'simplicity', 'sameness', 'uniformity'] },
    { word: 'pragmatic', definition: 'dealing with things sensibly', distractors: ['idealistic', 'impractical', 'foolish', 'random', 'careless'] },
    { word: 'substantiate', definition: 'to provide supporting evidence', distractors: ['deny', 'weaken', 'ignore', 'guess', 'fabricate'] },
    { word: 'ameliorate', definition: 'to make a bad situation better', distractors: ['worsen', 'damage', 'intensify', 'provoke', 'neglect'] },
    { word: 'paradigm', definition: 'a model for understanding something', distractors: ['exception', 'accident', 'error', 'detail', 'obstacle'] },
    { word: 'proliferate', definition: 'to increase rapidly in number', distractors: ['decline', 'shrink', 'vanish', 'decrease', 'diminish'] },
    { word: 'salient', definition: 'most noticeable or important', distractors: ['minor', 'hidden', 'irrelevant', 'subtle', 'trivial'] },
    { word: 'tenuous', definition: 'weak or uncertain', distractors: ['strong', 'solid', 'certain', 'secure', 'convincing'] },
    { word: 'ambivalent', definition: 'having mixed feelings', distractors: ['certain', 'decided', 'wholehearted', 'resolved', 'sure'] },
    { word: 'arduous', definition: 'requiring great effort', distractors: ['easy', 'effortless', 'simple', 'light', 'pleasant'] },
    { word: 'astute', definition: 'quick to notice and understand', distractors: ['dull', 'naive', 'careless', 'oblivious', 'slow'] },
    { word: 'candid', definition: 'honest and direct', distractors: ['evasive', 'dishonest', 'secretive', 'guarded', 'deceptive'] },
    { word: 'complacent', definition: 'too satisfied to improve', distractors: ['alert', 'concerned', 'ambitious', 'watchful', 'dissatisfied'] },
    { word: 'conspicuous', definition: 'easy to notice', distractors: ['hidden', 'subtle', 'inconspicuous', 'obscure', 'invisible'] },
    { word: 'discern', definition: 'to see something that is not obvious', distractors: ['overlook', 'confuse', 'ignore', 'miss', 'blur'] },
    { word: 'elusive', definition: 'hard to find or catch', distractors: ['obvious', 'available', 'clear', 'reachable', 'plain'] },
    { word: 'impartial', definition: 'fair and not favoring any side', distractors: ['biased', 'prejudiced', 'unfair', 'partial', 'one-sided'] },
    { word: 'resilient', definition: 'able to recover quickly', distractors: ['fragile', 'brittle', 'weak', 'defeated', 'rigid'] },
  ],

  10: [
    { word: 'abstruse', definition: 'difficult to understand', distractors: ['simple', 'clear', 'obvious', 'plain', 'easy'] },
    { word: 'acquiesce', definition: 'to accept something reluctantly', distractors: ['refuse', 'resist', 'reject', 'fight', 'deny'] },
    { word: 'capricious', definition: 'given to sudden changes of mood', distractors: ['steady', 'predictable', 'constant', 'stable', 'reliable'] },
    { word: 'demagogue', definition: 'a leader who manipulates people', distractors: ['servant', 'scholar', 'engineer', 'artist', 'farmer'] },
    { word: 'ephemeral', definition: 'lasting for a very short time', distractors: ['permanent', 'endless', 'eternal', 'lasting', 'fixed'] },
    { word: 'fastidious', definition: 'very attentive to detail', distractors: ['careless', 'sloppy', 'casual', 'lazy', 'reckless'] },
    { word: 'iconoclast', definition: 'someone who challenges beliefs', distractors: ['follower', 'conformist', 'traditionalist', 'imitator', 'bystander'] },
    { word: 'obfuscate', definition: 'to make something confusing', distractors: ['clarify', 'explain', 'simplify', 'reveal', 'illuminate'] },
    { word: 'perfunctory', definition: 'done with little effort', distractors: ['careful', 'thorough', 'passionate', 'detailed', 'eager'] },
    { word: 'circumlocution', definition: 'using more words than needed', distractors: ['brevity', 'clarity', 'directness', 'summary', 'precision'] },
    { word: 'deleterious', definition: 'causing harm or damage', distractors: ['beneficial', 'harmless', 'helpful', 'protective', 'useful'] },
    { word: 'equanimity', definition: 'calmness during stress', distractors: ['panic', 'anger', 'fear', 'agitation', 'confusion'] },
    { word: 'recalcitrant', definition: 'stubbornly resisting rules', distractors: ['obedient', 'cooperative', 'willing', 'agreeable', 'compliant'] },
    { word: 'anachronism', definition: 'something from a different time', distractors: ['contemporary', 'timeliness', 'relevance', 'accuracy', 'modernity'] },
    { word: 'dichotomy', definition: 'a division of two opposite parts', distractors: ['unity', 'blend', 'continuum', 'harmony', 'mixture'] },
    { word: 'egregious', definition: 'outstandingly bad', distractors: ['minor', 'excellent', 'slight', 'admirable', 'forgivable'] },
    { word: 'esoteric', definition: 'understood by only a small group', distractors: ['common', 'popular', 'simple', 'mainstream', 'accessible'] },
    { word: 'magnanimous', definition: 'generous and noble', distractors: ['petty', 'selfish', 'vindictive', 'mean', 'spiteful'] },
    { word: 'quixotic', definition: 'unrealistically idealistic', distractors: ['practical', 'realistic', 'sensible', 'cautious', 'pragmatic'] },
  ],
};